const rawData = {
    "Il Colpo": {
        "riassunto":
            [`Un bersaglio. Ministero della Conservazione.\n
            Un luogo. Uno dei magazzini per lo stoccaggio del contrabbando vicino alla Stazione Gaddoc.\n
            Una situazione. Una rete di contrabbando di essenza di spirito, proprio ieri, è stata beccata dai Guardiani presso la Stazione di Gaddoc.\n
            Un vettore ovvio per il piano. Laroze può farsi assumere in nero come guardia privata. Vi farà entrare dal retro, per una fetta dei guadagni.\n
            \n
            Informazioni più precise:\n
            Fazioni collegate e cosa vogliono o necessitano. Quell’essenza era stata pagata dall’Alveare. Vogliono ciò che è loro.\n
            Un vettore non così scontato per il piano. Le essenze di spirito possono essere richiamate attraverso il campo spettrale... in teoria.\n
            Segreti interessanti, un collegamento a un’opportunità alternativa. È molto probabile che i Guardiani mettano in sicurezza l’essenza catturata con protezioni arcane. I Riconciliati aborrono lo scambio di essenza e potrebbero essere un potenziale alleato o nemico, a seconda di quello farete.\n`],
        "Opportunità":[
            "I vostri clienti più prestigiosi sono stanchi di venire nel vostro territorio per una dose. Create una vetrina in una parte più onesta della città (o al contrario per i clienti di classe sociale inferiore)."
            ,"Il culto di un dio dimenticato vi fa un'offerta per una collaborazione: possono rendere il vostro prodotto più appetibile in cambio di... un trattamento speciale."
            ,"Una nobile dilettante sempre sulla cresta dell'onda sta bazzicando nella vostra area con il suo entourage di leccapiedi, in cerca della 'prossima hit' da provare."
            ,"Un ardente predicatore fa proclami contro il vostro prodotto per le strade, abbassando la richiesta. Ma vi sembra di riconoscerlo come un vostro cliente..."
            ,"La gang che operava sul vostro territorio anni fa è tornata dalle Isole del Pugnale e si aspetta di tornare ai suoi affari come se nulla fosse."
            ,"Inizia ad apparire nelle strade un'imitazione del vostro prodotto, a un prezzo ribassato. Il vostro fornitore vi sta tagliando fuori'"
            ,"I trafficanti vogliono eliminare tutti gli intermediari nella filiera e gestire le cose direttamente con voi."
            ,"I fantasmi dei vostri 'ex' clienti sono improvvisamente richiamati a voi, smaniosi per la loro dose."
            ,"Una famigerata cacciatrice di leviatani ha gusti che... solitamente non soddisfate, ma è disposta a pagare davvero molto bene."
            ,"Una Giubba Blu ha ucciso il suo ultimo spacciatore per aver 'spinto troppo in là il loro rapporto', e si rivolge alla banda come fonte alternativa."
            ,"Una brutale gang di feroci assassini ha 'ripulito' il covo del vizio di un rivale. Ora vogliono che siate voi a occuparvi della gestione."
            ,"Una figura mascherata vi paga profumatamente per l'opportunità di uccidere uno dei vostri clienti abituali mentre è... distratto."
            ,"Un assassino arcano sta bersagliando fruitori e spacciatori, lasciando Simulacri a vagare per la città."
            ,"Un operatore solitario sta distribuendo una versione molto più popolare del vostro prodotto."
            ,"Un membro del Consiglio Cittadino sta mettendo al vaglio un divieto assoluto per un prodotto illecito; potrebbero farsi convincere a fare in modo che sia il vostro, mandando la domanda alle stelle."
            ,"Una nuova gang del vizio sta facendo delle mosse molto scaltre e intelligenti. Le voci dicono che siano guidati dal fantasma di un criminale leggendario."
            ,"Gli studenti dell'Accademia di Doskvol hanno dimostrato interesse per la vostra merce, ma dovete consegnarla direttamente, superando la sicurezza gestita dalle Giubbe Blu."
            ,"Un leggendario truffatore e la sua banda stanno colpendo diversi magazzini. È stata messa una taglia sulle loro teste: riuscirete a rivendicarla'"
        ],
        "Cliente/Bersaglio":[
            "Nobile"
            ,"Ufficiale"
            ,"Banchiere"
            ,"Capitano"
            ,"Posseduto"
            ,"Simulacro"
            ,"Accademico"
            ,"Studioso"
            ,"Vampiro"
            ,"altro Non Morto"
            ,"Sacerdote"
            ,"Cultista"
            ,"Dottore"
            ,"Alchimista"
            ,"Mercenario"
            ,"Teppista"
            ,"Rivoluzionario"
            ,"Rifugiato"
            ,"Spacciatore"
            ,"Fornitore"
            ,"Corriere"
            ,"Marinaio"
            ,"Spia"
            ,"Informatore"
            ,"Ricettatore"
            ,"Scommetitore"
            ,"Boss Criminale"
            ,"Mercante"
            ,"Negoziante"
            ,"Fantasma di (tira ancora)"
            ,"Sussurro"
            ,"Cultista"
            ,"Trafficante"
            ,"Ladro"
            ,"Manovale"
            ,"Commerciante"
            ,"Artista"
            ,"Scrittore"
            ,"Magistrato"
            ,"Capo Distretto"
            ,"Demone (mascherato)"
            ,"Collezionista Occulto"
            ,"Conestabile"
            ,"Ispettore"            
        ],
        "lavoro":[
            "Raccolta"
,"Piazzamento"
,"Impersona"
,"Depista"
,"Distruggi"
,"Deturpa"
,"Crea"
,"Rianima un Simulacro"
,"Rapina"
,"Furto"
,"Rapina"
,"Rapina a mano armata"
,"Terrorizza"
,"Estorici"
,"Incursione"
,"Difesa"
,"Estrai Essenza"
,"Trova"
,"Nascondi"
,"Piazza"
,"Rimuovi Rune"
,"Avvelena"
,"Simula Incidente"
,"Scorta"
,"Sicurezza"
,"Cerimonia / Ferma un Rituale"
,"Bandisci"
,"Evoca"
,"Pedinamento"
,"Sorveglianza"
,"Sabotaggio"
,"Dolo"
,"Sparizione"
,"Riscatto"
,"Ricatta"
,"Discredita"
,"Maledici"
,"Santifica"
,"Assasinio"
,"Contrabbando"
,"Corriere"
,"Truffa"
,"Spionaggio"
,"Negozia"
,"Minaccia"
        ],
        "modifica o complicazione":[
            "Un elemento e' una copertura perpratiche eretiche di un culto"
,"Il lavoro e' un test per un lavoro successivo"
,"Il luogo si muove (il sito cambia, e' suun veicolo, ecc.)"
,"Il lavoro richiede un viaggio in mare"
,"Il lavoro porta avanti gli interessi segruenti di un prestigioso mercante"
,"Il lavoro richiede di viaggiare in elettrotreno"
,"Il lavoro porta avanti gli interessi segreti di un vampiro"
,"Il luogo e' usato da una gang pericolosa"
,"Il lavoro porta avanti gli interessi segreti di un boss criminale"
,"Un elemento e' un facciata per un'impresa criminale"
,"Il lavoro porta avanti gli interessi segreti di un ufficiale cittadino"
,"Il lavoro porta avanti gli interessi segreti di un demone"
,"Bisogna visitare le Terre Morte"
,"Il lavoro porta avanti gli interessi segreti di un rivoluzionario"
,"Spiriti impazziti posseggono alcuni/molti/tutti o coinvolti"
,"Un occultista ha previsto il colpo e ha avvertito le parti interessate"
,"Spiriti impazziti infestano il luogo"
,"Il lavoro e' una trappola impostata dai vostri nemici"

        ],
        "LEGATO A UNA PERSONA":[
            ,"Strano Fantasma, Demone, Dio"
,"PG Amico"
,"PG Rivale"
,"PG Fornitore del Vizio"
,"Città Volto noto di Doskvol"
,"Banda Contatto"
        ],
        "E FAZIONI":[
            "Ulf Ironborn"
        ,"Marinai o Portuali"
        ,"Cacciatori di Leviatani"
        ,"Lord Scurlock"
        ,"Ministero della Conservazione"
        ,"Il Consiglio o LaFondazione"
        ,"Rifugiati Skovlanesi"
        ,"Gli Dei Dimenticati"
        ,"Folgoratori"
        ,"Esercito Imperiale"
        ,"Guardarotaie o La Brigata"
        ,"Un Consolato"
        ,"Le Giubbe Grigie"
        ,"Gli Spettri"
        ,"Le Fioche Sorelle"
        ,"Sentiero o Riconciliati"
        ,"Messi o Gazzettini"
        ,"La Chiesa dell'Estasi"
        ,"Predoni delle Terre Morte"
        ,"Giubbe Blu o Ispettori"
        ,"Guardiani diSpiriti"
        ,"Le Fusciacche Rosse"
        ,"Il Circolo della Fiamma"
        ,"Le Roncole"
        ,"La Signoradel Pianto"
        ,"I Corvi"
        ,"I Perduti"
        ,"I Lampionari"
        ,"I Segugi della Nebbia"
        ,"Prigione di Ironhook"
        ,"Tritasangue"
        ,"Operai o Servitori"
        ,"L'Alveare"
        ,"Gondolieri o Nocchieri"
        
        ]
    }
}