const rawData = {
"Demone":{
"Nome":[
"Sevraxis"
,"Korvaeth"
,"Azarax"
,"Kylastra"
,"Oryxus"
,"Zalvroxos"
,"Ahazu"
,"Arkeveron"
,"Vaskari"
,"Ixis"
,"Esketra"
,"Kyronax"
,"Argaz"
,"Voldranai"
,"Ardranax"
,"Kethtera"
,"Tyraxis"
]
,"Aspetto1":[
"Protusioni ossee"
,"Icore gocciolante"
,"Occhi o marchiature ardenti"
,"Liquidi gelano, bollono, diventano sangue o cenere"
,"Capelli o pelliccia"
,"Piume"
,"Ali di cuoio"
,"Scaglie (onice, iridescenti, cristalline, metalliche, ecc.)"
,"(ondeggiano come sott'acqua, bruciano di fiamma freddo, ecc.)"
,"Le piante avvizziscono o fioriscono"
,"Luci fioche o bagliori"
,"Numerose braccia"
,"Ingranaggi si fermano"
,"Tanti occhi"
,"Coda a frustra"
,"Artigli affilati"
,"Tentacoli"
,"Occhi da squalo"
,"Spine"
,"Guscio duro, placche metalliche"
]
,"Tratti":[
"Sfrontato"
,"Rivelatorio"
,"Competente"
,"Folle"
,"Vendicativo"
,"Perspicace"
,"Inqusitorio"
,"Bizzarro"
,"Curioso"
,"Territoriale"
,"Educativo"
,"Volatile"
,"Suscettibile"
,"Insistente"
,"Affascinante"
,"Guida"
,"Aggressivo"
,"Profetico"
,"Dominante"
,"Arrabbiato"
,"Violento"
,"Astuto"
,"Reattivo"
,"Caotico"
,"Ingannevole"
,"Distruttivo"
,"Geloso"
,"Vile"
,"Esigente"
,"Pazzo"
,"Isterico"
,"Vero"
,"Selvaggio"
,"Crudele"
,"Fugace"
,"Disperato"
]
,"Effetti secondari":[
"Strane ombre"
,"Vento di tempesta"
,"Voci nella testa"
,"Vento rapido"
,"Brina, gelo"
,"Suoni tempestosi"
,"Foschia, nebbia"
,"Vento"
,"Echi visivi intensi"
,"Scarica"
,"Elettrica"
,"Freddo"
,"Fulmini"
,"Buio completo"
,"Ombre avvolgenti"
,"Ombre inquietanti"
,"Nebbia gelante"
,"Tenui echi"
,"Magnetismo intenso"
,"Tenui visioni del passato"
]
,"Aspetto2":[
"Caratteristiche elementali"
,"Mostruoso"
,"Umanoide"
,"Animale"
,"Caratteristiche bestiali"
,"Amorfo"
]
,"Affinità":[
"Tempesta, vento"
,"Cielo, stelle"
,"Mare, acqua"
,"Terra, metallo"
,"Fuoco, fumo"
,"Oscurità"
]
,"Desiderio":[
"Sofferenza"
,"Vendetta"
,"Caos"
,"Manipolazione"
,"Controllo"
,"Corruzione"
,"Guerra"
,"Delirio"
,"Potere"
,"Omicidio"
,"Brutalità"
,"Conoscenza"
,"Libertà"
,"Successo"
,"Paura"
,"Giustizia"
,"Inganno"
,"Piacere"
]
,"Orrori evocati":[
"Essere metallico"
,"Nuvola di cenere ardente"
,"Geometria impossibile"
,"Globo divorante"
,"Animale mostruoso"
,"Brandelli di carne"
,"Viscere pulsanti"
,"Pietra animata"
,"Essere liquido"
,"Scheletro di vetro nero"
,"Sfere scintillanti"
,"Artigli sferzanti"
,"Cefalopode fluttuante"
,"Vibrazioni tremolanti"
,"Rocchetto di spine"
,"Luci ipnotiche"
,"Essere scuoiato"
,"Serpiforme"
,"Essere fiammeggiante"
,"Oscurità asfissiante"
,"Pianta infestante"
,"Essere d'ombra"
,"Ingranaggi contorti"
,"Muco vorticante"
,"Foschia psichica"
,"Massa informe"
,"Catrame putrido"
,"Fuoco freddo"
,"Nube tossica"
,"Argento vivo"
,"Vapori nauseabondi"
,"Schegge cristalline"
,"Bava viscida"
,"Sciame di insetti"
,"Insettoide"
,"Essere radiante"
]
}
,"Edifici":{
"Materiale":[
"Grigio"
,"Mattone"
,"Blocchi di pietra"
,"Intonaco e legno"
,"Lamiera"
,"Assi di legno"
,"Pietra e legno"
]
,"Dettagli1":[
"Lavorazioni della pietra"
,"Lavorazioni del legno"
,"Giardino"
,"Ferro battuto"
,"Piastrelle"
,"Lavorazioni di vetro"
]
,"Uso":[
"Laboaratorio"
,"Magazzino"
,"Bagno pubblico"
,"Grotta"
,"Stazione di guardia"
,"Grotta"
,"Fabbrica"
,"Bagno pubblico"
,"Birrificio"
,"Appartamenti"
,"Fabbrica"
,"Piccola casa"
,"Molo"
,"Bordello"
,"Sartoria"
,"Ospizio"
,"Birrificio"
,"Appartamenti"
,"Bordello"
,"Caffé"
,"Giardino di funghi"
,"Macellaio"
,"Tatuatore"
,"Magazzino"
,"Case popolari"
,"Magazzino"
,"Giardino di funghi"
,"Raffineria"
,"Arene da combattimento"
,"Piazza, fontana"
,"Fabbrica"
,"Laboaratorio"
,"Bordello"
,"Taverna"
,"Altare"
,"Appartamenti"
,"Appartamenti"
,"Bisca"
,"Molo"
,"Sartoria"
,"Taverna"
,"Panettiere"
,"Cerusico"
,"Fabbrica"
,"Altare"
,"Speziale"
,"Tatuatore"
,"Case a schiera"
,"Fucina"
,"Molo"
,"Raffineria"
,"Giardino di funghi"
,"Piccola casa"
,"Allevamento di anguille"
,"Fabbrica"
,"Centrale energetica"
,"Laboaratorio"
,"Macellaio"
,"Stalle per capre"
,"Sartoria"
,"Ospizio"
,"Mercato"
,"Tribunale, galera"
,"Arene da combattimento"
,"Case a schiera"
,"Tatuatore"
,"Bordello"
,"Fucina"
,"Grotta"
,"Allevamento di anguille"
,"Grotta"
,"Vinaio"
,"Piccola casa"
,"Fucina"
,"Rovina"
,"Locanda"
,"Cerusico"
,"Piazza, fontana"
,"Raffineria"
,"Allevamento di anguille"
,"Panettiere"
,"Rovina"
,"Altare"
,"Macellaio"
,"Fucina"
,"Maestro artigiano"
,"Bordello"
,"Mercato"
,"Cerusico"
,"Altare"
,"Bagno pubblico"
,"Allevamento di anguille"
,"Panettiere"
,"Fabbrica"
,"Covo di tossici"
,"Bagno pubblico"
,"Panettiere"
,"Laboaratorio"
,"Giardino di funghi"
,"Tribunale, galera"
,"Bordello"
,"Ospizio"
,"Cisterna"
,"Stalle per capre"
,"Mercato"
,"Gioielliere"
,"Tribunale, galera"
,"Giardino di funghi"
,"Bisca"
,"Stalle per capre"
,"Grotta"
,"Galleria d'arte"
,"Molo"
,"Stazione di guardia"
,"Piazza, fontana"
,"Appartamenti"
,"Spiritualista"
,"Panettiere"
,"Giardino radiante"
,"Mercato"
,"Stazione di guardia"
,"Bagno pubblico"
,"Panettiere"
,"Stazione di guardia"
,"Birrificio"
,"Ospizio"
,"Raffineria"
,"Cerusico"
,"Mercato"
,"Raffineria"
,"Birrificio"
,"Magazzino"
,"Bordello"
,"Macellaio"
,"Taverna"
,"Cerusico"
,"Tatuatore"
,"Birrificio"
,"Bagno pubblico"
,"Piazza, fontana"
,"Rovina"
,"Altare"
,"Giardino di funghi"
,"Locanda"
,"Covo di tossici"
,"Altare"
,"Bisca"
,"Covo di tossici"
,"Fucina"
,"Locanda"
,"Cerusico"
,"Tribunale, galera"
,"Mercato"
,"Aia"
,"Parco"
,"Birrificio"
,"Covo di tossici"
,"Sartoria"
,"Macellaio"
,"Stalle per capre"
,"Aia"
,"Fucina"
,"Sartoria"
,"Case popolari"
,"Bisca"
,"Macellaio"
,"Covo di tossici"
,"Magazzino"
,"Grotta"
,"Merceria"
,"Tatuatore"
,"Piazza, fontana"
,"Piazza, fontana"
,"Case a schiera"
,"Allevamento di anguille"
,"Tabaccaio"
,"Covo di tossici"
,"Mercato"
,"Monumento"
,"Case popolari"
,"Sartoria"
,"Piccola casa"
,"Macellaio"
,"Locanda"
,"Cerusico"
,"Accademia"
,"Molo"
,"Raffineria"
,"Bisca"
,"Molo"
,"Allevamento di anguille"
,"Bisca"
,"Ristorante"
,"Giardino di funghi"
,"Taverna"
,"Magazzino"
,"Cerusico"
,"Ospizio"
,"Stalle per capre"
,"Tempio"
,"Rovina"
,"Aia"
,"Tatuatore"
,"Fabbrica"
,"Mercato"
,"Case popolari"
,"Locanda"
,"Arene da combattimento"
,"Bar, lounge"
,"Bagno pubblico"
,"Baracca"
,"Rovina"
,"Case a schiera"
,"Arene da combattimento"
,"Covo di tossici"
,"Sartoria"
,"Piccola casa"
,"Teatro"
,"Grotta"
,"Estetista"
,"Magazzino"
,"Macellaio"
,"Raffineria"
,"Panettiere"
,"Allevamento di anguille"
,"Taverna"
,"Sartoria"
,"Locanda"
,"Ospizio"
,"Teatro lirico"
,"Fabbrica"
,"Fucina"
,"Mercato"
,"Laboaratorio"
,"Baracca"
,"Ospizio"
,"Ospizio"
,"Rovina"
,"Raffineria"
,"Birrificio"
,"Stazione di guardia"
,"Allevamento di anguille"
,"Taverna"
,"Case popolari"
,"Stalle per capre"
,"Tribunale, galera"
,"Arene da combattimento"
,"Altare"
,"Bordello"
,"Stalle per capre"
,"Cerusico"
,"Bagno pubblico"
,"Bordello"
,"Stalle per capre"
,"Baracca"
,"Rovina"
,"Piazza, fontana"
,"Locanda"
,"Case popolari"
,"Stazione di guardia"
,"Ospizio"
,"Case a schiera"
,"Baracca"
,"Arene da combattimento"
,"Arene da combattimento"
,"Piccola casa"
,"Stazione di guardia"
,"Banca"
,"Taverna"
,"Bordello"
,"Tribunale, galera"
,"Arene da combattimento"
,"Laboaratorio"
,"Giardino di funghi"
,"Villa"
,"Stalle per capre"
,"Ospizio"
,"Bisca"
,"Bagno pubblico"
,"Bisca"
,"Molo"
,"Laboaratorio"
,"Appartamenti"
,"Tatuatore"
,"Tatuatore"
,"Allevamento di anguille"
,"Aia"
,"Aia"
,"Fabbrica"
,"Covo di tossici"
,"Tribunale, galera"
,"Laboaratorio"
,"Tribunale, galera"
,"Case a schiera"
,"Panettiere"
,"Stazione di guardia"
,"Negozio di libri"
,"Appartamenti"
,"Locanda"
,"Bisca"
,"Baracca"
,"Aia"
,"Casa padronale"
,"Aia"
,"Piccola casa"
,"Macellaio"
,"Giardino di funghi"
,"Distilleria"
,"Aia"
,"Stazione di guardia"
,"Fabbrica"
,"Piazza, fontana"
,"Taverna"
,"Appartamenti"
,"Covo di tossici"
,"Piccola casa"
,"Tatuatore"
,"Aia"
,"Mercato"
,"Baracca"
,"Case popolari"
,"Piazza, fontana"
,"Case a schiera"
,"Appartamenti"
,"Piccola casa"
,"Molo"
,"Locanda"
,"Arene da combattimento"
,"Stalle"
,"Case a schiera"
,"Rovina"
,"Bisca"
,"Aia"
,"Grotta"
,"Taverna"
,"Altare"
,"Rovina"
,"Locanda"
,"Case a schiera"
,"Fucina"
,"Bagno pubblico"
,"Covo di tossici"
,"Baracca"
,"Raffineria"
,"Fucina"
,"Fucina"
,"Arene da combattimento"
,"Allevamento di anguille"
,"Alchimista"
,"Panettiere"
,"Grotta"
,"Altare"
,"Tribunale, galera"
,"Case popolari"
,"Baracca"
,"Tatuatore"
,"Panettiere"
,"Sartoria"
,"Birrificio"
,"Stalle per capre"
,"Tribunale, galera"
,"Case popolari"
,"Magazzino"
,"Casa galleggiante"
,"Magazzino"
,"Grotta"
,"Appartamenti"
,"Laboaratorio"
,"Piccola casa"
,"Laboaratorio"
,"Molo"
,"Molo"
,"Appartamenti"
,"Mercato"
,"Sartoria"
,"Giardino di funghi"
,"Case a schiera"
,"Altare"
,"Case popolari"
,"Raffineria"
,"Baracca"
,"Macellaio"
,"Taverna"
,"Archivio"
,"Magazzino"
,"Piazza, fontana"
,"Birrificio"
,"Fiorista"
,"Rovina"
,"Baracca"
,"Stazione di guardia"
,"Clinica"
,"Residenza"
,"Stazione di guardia"
,"Cerusico"
,"Birrificio"
]
,"Dettagli2":[
"Sacrario, altare"
,"Polvere, detriti"
,"Finestre blindate"
,"Percorsi panoramici"
,"Arredamento utilitaristico"
,"Acqua gocciolante"
,"Lucerne fumose"
,"Luci elettriche crepitanti"
,"Meccanismo ticchettante"
,"Basso, angusto"
,"Rifiniture eleganti"
,"Accogliente, caldo"
,"Scala a chiocciola, scaletta"
,"Tappezzerie, quadri"
,"Porte segrete"
,"Austerità spartana"
,"Usura, danni"
,"Fuochi scoppiettanti"
,"Cantine"
,"Robusto, tranquillo"
,"Balconi"
,"Logoro, consumato"
,"Pavimento scricchiolante"
,"Piante, fiori"
,"Tende pesanti, tappeti spessi"
,"Arredi di antiquariato"
,"Spifferi, freddo"
,"Ammasso di curiosità"
,"Barriere spiritiche, vecchie rune"
,"Traballante, sgangherato"
,"A volta, spazioso"
,"Passerelle"
,"Rigoglioso, comodo"
,"Ruvida essenzialità"
,"Artefatti bizzarri"
,"Strani arnesi"
]
,"Oggetti1":[
"Sedie"
,"Diagrammi"
,"Mappe"
,"Librerie"
,"Orologio"
,"Scrivania"
,"Scrivania"
,"Libri"
,"Quaderni"
,"Cartigli"
,"Armadio"
,"Documenti"
,"Calamaio"
,"Scaffali"
,"Lampada"
,"Grafici"
,"Lavagna"
,"Tavolo"
]
,"Oggetti2":[
"Divano"
,"Letto"
,"Poltrone"
,"Carillion"
,"Baule"
,"Tavolo"
,"Brocca"
,"Drappeggi"
,"Lampade"
,"Ottomana"
,"Cuscini"
,"Lavello"
,"Dormeuse"
,"Branda"
,"Toilette"
,"Sgabelli"
,"Scrittoio"
,"Specchio"
]
,"Oggetti3":[
"Pentolame"
,"Posate"
,"Lavandino"
,"Carte"
,"Tavolo da pranzo"
,"Giochi"
,"Bivacco"
,"Whisky"
,"Gabinetto"
,"Spezie"
,"Dispensa"
,"Ganci"
,"Vino"
,"Dadi"
,"Bancone"
,"Birra"
]
,"Oggetti4":[
"Piedistallo"
,"Libro"
,"Candele"
,"Spartiti"
,"Voliera"
,"Poltrona"
,"Dipinti"
,"Tappeto"
,"Vasi"
,"Caminetto"
,"Strumenti"
,"Tende"
,"Statua"
,"Campana"
,"Penna"
]
,"Oggetti5":[
"Armi"
,"Stracci"
,"Bruciatore"
,"Strumenti"
,"Munizioni"
,"Banco da lavoro"
,"Fiale"
,"Beaker"
,"Strumenti medici"
]
}
,"Luogo":{
"Luoghi":[
"Draga di Dunslough"
,"Ferriera (case popolari) di Coalridge"
,"Ponte bowmore a Brightstone"
,"Stazione ferroviaria di gaddok"
,"Sede della guardia cittadina di Brightstone"
,"Università di Charterhall"
,"Tenute di collina per i supervisori di Barrowcleft"
,"Via della cancelleria (strutture governative) Charterhall"
,"Archivi degli echi a Charterhall"
,"Ponte barrow (Barrowcleft)"
,"Mercato di Barrowcleft"
,"Brkstone (+redisdenziale di Duskwall) a Coalridge"
,"Gli scampoli (stoffe lavandaie) a Charhollow"
,"Vecchio porto 'nord'"
,"Ghetto di Dunslough"
,"Da kellen (pub) Charhollow"
,"Groviglia (nave affondata, quartiere galleggiante) a Crow's foot"
,"Fabbrica di binari a Coalridge"
,"Campo lavoro di dunvil a Dunslough"
,"Accampamento di barboni a Crow's foot"
,"Opulento teatro/ristorante a Brightstone"
,"Il quartiere dei lavoratori di Barrowcleft"
,"Villa capitano d'industria a Charterhall"
,"Il nido (quartier generale corvi) a Crow's foot"
,"Mercado di Charhollow"
,"Stazione giubbe blu a Crow's foot"
,"Casa strathmill (orfanotrofio) a Crow's foot"
,"Accademia della fusciacca rossa a Crow's foot"
,"Villa nobiliare di wott a Brightstone"
,"Le miniere di Barrowcleft"
,"Casa strangford Charhollow"
,"Allevamenti di anguille di Dunslough"
,"Fabbrica di carrozze a Coalridge"
,"Mercato argenteo di Brightstone"
,"Parco jayan (studenti) Charterhall"
,"Il secchio (locale) a Crow's foot"
,"Case forza lavoro (marinai, nocchieri,anguillari...) Charhollow"
,"Magazzini adibiti a rivoluzione Charhollow"
,"Vecchie mura di Charterhall"
,"Fattoria radiante di Barrowcleft"
,"Crematori di bellwather Charterhall"
,"La melma (cava di fango) Dunslough"
,"Case forza lavoro (servitù,portuali,allevatori...) Charhollow"
,"Il sanctorium di Brightstone (estasi carne)"
,"La ferrovia spettrale a Coalridge"
,"Prigione di ironhook a Dunslough"
,"Villabaracca di vandra a Dunslough"
,"Miniera di Coalridge"
,"Parco dell'unità di Brightstone"
,"Vecchio deposito di Coalridge"
,"Villa per festa stravagante"
,"Il velo (club lussuoso, strano) Nightmarket"
,"Dundridge & figli (sartoria) Nightmarket"
,"Corse di segugi di vreen Nightmarket"
,"Dente del diavolo (taverna, menù alchemico) Nightmarket"
,"Una villetta a schiera a Nightmarket"
,"Negozi con insegne al neon a Nightmarket"
,"Mercante di saponi di lusso a Nightmarket"
,"Compagnia di punta nord al porto"
,"Largo inchiostro (tatuatori) al porto"
,"Saltford e la sua gang(mortaccisua) al porto"
,"Il serraglio (zoo?) al porto"
,"Stazione al porto"
,"Nave attraccata al porto"
,"Magazzini al porto"
,"Casa rowan a 6torri"
,"Parco mistshore (suicidi/infestato) a 6torri"
,"Maniero scurlock a 6torri"
,"Braccia signora del pianto (dormitorio) a 6torri"
,"Casa abbandonata a 6torri"
,"La prugna dorata (ristorante) a 6torri"
,"Casa di flint a 6torri"
,"I terreni della folgore (circo) a Silkshore"
,"La bonaccia (negozi e bordelli) a Silkshore"
,"Colle fogrest (comunità bohemienne) a Silkshore"
,"Parco ankhayat (zona festival) a Silkshore"
,"Casa levyra (legge la mente/futuro) a Silkshore"
,"Cervo argentato (casinò) a Silkshore"
,"La lanterna rossa (bordello) a Silkshore"
]
}    
,"Persona":{
"Retaggio":[
"Iruviano"
,"Skovlandese"
,"Akorosiano"
,"Akorosiano"
,"Severosiano"
,"Akorosiano"
,"Tycherosiano"
,"Akorosiano"
,"Akorosiano"
,"Akorosiano"
,"Skovlandese"
,"Isolano"
]
,"Nome":[
"Arquo"
,"Grine"
,"Skannon,"
,"Weaver"
,"Orlan,"
,"Roethe,"
,"Cyrene,"
,"Casslyn,"
,"Crowl"
,"Arlyn,"
,"Syra"
,"Hix"
,"Vestine,"
,"Cross"
,"Odrienne"
,"Una"
,"Daphnia"
,"Amosen,"
,"Timoth,"
,"Candra,"
,"Brena"
,"Arvus"
,"Myre"
,"Polonia"
,"Sesereth"
,"Lizete,"
,"Vey"
,"Ashlyn,"
,"Veretta"
,"Thena"
,"Talitha,"
,"Milos"
,"Veleris"
,"Sethla"
,"Lenia"
,"Carissa"
,"Andrel"
,"Morlan,"
,"Tocker"
,"Naria,"
,"Lucella"
,"Aldo"
,"Edlun,"
,"Phin"
,"Narcus"
,"Lauria"
,"Arden"
,"Stev"
,"Emeline"
,"Noggs"
,"Remira"
,"Holtz"
,"Vond,"
,"Corille,"
,"Kelyr,"
,"Lorette"
,"Volette"
,"Kamelin"
,"Clave"
,"Vaurin,"
,"Laudius,"
,"Kobb"
,"Tesslyn"
,"Wester"
,"Helles,"
,"Ring"
,"Cavelle"
,"Stavrul"
,"Kristov"
,"Carro"
,"Adric"
,"Quess,"
,"Lynthia,"
,"Bricks"
,"Brance,"
,"Brace"
,"Drav"
,"Mara"
,"Branon"
,"Zamira."
]
,"Alias":[
"Tintinnio"
,"Uncino"
,"Corvo"
,"Sperone"
,"Martello"
,"Mazzetta"
,"Dozzina"
,"Frusta"
,"Campanaccio"
,"Puleggia"
,"Nebbia"
,"Acqua cheta"
,"Scheggia"
,"Squillo"
,"Eco"
,"Grillo"
,"Pistolero"
,"Volpe"
,"Gramigna"
,"Acciarino"
,"Rana"
,"Splendido"
,"Rubino"
,"Cuore tenero"
,"Orco"
,"Pallida"
,"Stecco"
,"Croce"
,"Canto"
,"Insetto"
,"Artiglioago"
,"Catorcio"
,"Ammaccato"
,"Scorticatore"
,"Brinamorsa"
,"Spire"
]
,"Cognome":[
"Strathmill"
,"Haig"
,"Bowman"
,"Walund"
,"Athanoch"
,"Boden"
,"Vale"
,"Dalmore"
,"Kardera"
,"Basran"
,"Lomond"
,"Morriston"
,"Rowan"
,"Brogan"
,"Dunvil"
,"Penderyn"
,"Maroden"
,"Arran"
,"Templeton"
,"Ankhayat"
,"Farros"
,"Hellyers"
,"Danfield"
,"Skelkallan"
,"Tyrconnell"
,"Prichard"
,"Booker"
,"Grine"
,"Michter"
,"Clelland"
,"Clermont"
,"Jayan"
,"Helker"
,"Slane"
,"Keel"
,"Coleburn"
,"Comber"
,"Sevoy"
,"Welker"
,"Daava"
,"Breakiron"
,"Jeduin"
,"Skora"
,"Kinclaith"
,"Helles"
,"Karstas"
,"Kessarin"
,"Strangford"
]    
,"Aspetto":[
"Uomo"
,"Donna"
,"Donna"
,"Ambiguo"
,"Uomo"
,"Uomo"
,"Celato"
,"Donna"
]
,"Aspetto 2":[
"Consunto"
,"Selvaggio"
,"Strano"
,"Grosso"
,"Pallido"
,"Basso"
,"Sfigurato, menomato"
,"Ombroso"
,"Tozzo"
,"Giovane"
,"Sexy"
,"Delicato"
,"Alto"
,"Capelli lunghi, barba, parrucca"
,"Nerboruto"
,"Prostetica, zoppo"
,"Ricurvo"
,"Paffuto"
,"Rasato, calvo"
,"Smilzo"
,"Tatuato"
,"Ossuto"
,"Atletico"
,"Elegante"
,"Carino"
,"Grezzo"
,"Logorato"
,"Sfregiato"
,"Raffinato"
,"Occhiali, monocolo"
,"Cesellato"
,"Banale"
,"Vecchio"
,"Appariscente"
,"Affascinante"
,"Adorabile"
]
,"Stile":[
"Anfibi da lavoro"
,"Drappeggi"
,"Cappotto"
,"Cappuccio"
,"Mantella"
,"Gonna e camicia"
,"Guanti pesanti"
,"Uniforme"
,"Sedia a rotelle"
,"Camicia"
,"Leggings"
,"Maschera"
,"Cintura spessa"
,"Stampelle"
,"Tunica grezza"
,"Pastrano"
,"Bretelle"
,"Tricorno"
,"Mantello corto"
,"Pantaloni eleganti"
,"Sciarpa lunga"
,"Completo"
,"Bastone"
,"Body di anguilla"
,"Abito aderente"
,"Maschera"
,"Stivali morbidi"
,"Cappello di lana"
,"Grembiule"
,"Pelliccia"
,"Stracci"
,"Cinturone"
,"Impermeabile"
,"Mantello pesante"
,"Pelli"
,"Giacca aderente"
,"Stivali alti"
]
,"Obiettivi":[
"Svolta"
,"Conoscenza"
,"Rispetto"
,"Potere"
,"Prestigio, fama"
,"Libertà"
,"Caos, distruzione"
,"Vendetta"
,"Felicità"
,"Giustizia"
,"Infamia, paura"
,"Potere"
,"Successo"
,"Piacere"
,"Controllo"
,"Cooperazione"
,"Benessere"
,"Autorità"
,"Amore"
]
,"Metodi preferiti":[
"Furto"
,"Lavoro duro"
,"Arcano"
,"Sabotaggio"
,"Manipolazione"
,"Ricatto"
,"Lavoro di squadra"
,"Violenza"
,"Strategia"
,"Legge, politica"
,"Caos"
,"Negoziazione"
,"Minacce"
,"Alchimia"
,"Commercio"
,"Studio"
,"Spionaggio"
,"Sotterfugio"
]
,"Professioni":[
"Gondoliere"
,"Mercante"
,"Birraio"
,"Artista"
,"Criminale"
,"Muratore"
,"Muratore"
,"Ricamatore"
,"Carpentiere navale"
,"Calzolaio"
,"Muratore"
,"Pellaio"
,"Panettiere"
,"Barbiere"
,"Macellaio"
,"Autista"
,"Pellaio"
,"Carpentiere"
,"Carpentiere"
,"Venditore"
,"Impiegato"
,"Servitore"
,"Messaggero"
,"Barbiere"
,"Calzolaio"
,"Marinaio"
,"Autista"
,"Impiegato"
,"Carradore"
,"Mercante"
,"Mercante"
,"Tipografo"
,"Pastore di capre"
,"Vetraio"
,"Messaggero"
,"Musicista"
,"Fabbro"
,"Pellaio"
,"Pescatore"
,"Fabbro"
,"Servitore"
,"Coltivatore"
,"Falegname"
,"Barbiere"
,"Calzolaio"
,"Tappezziere"
,"Secondino"
,"Criminale"
,"Birraio"
,"Tessitore"
,"Criminale"
,"Tintore"
,"Cordaio"
,"Ricamatore"
,"Fabbro"
,"Pellaio"
,"Tappezziere"
,"Gondoliere"
,"Carradore"
,"Marinaio"
,"Messaggero"
,"Tappezziere"
,"Difensore"
,"Mercante"
,"Tessitore"
,"Pastore di capre"
,"Droghiere"
,"Inventore"
,"Ripara tetti"
,"Impiegato"
,"Coltivatore"
,"Barbiere"
,"Calzolaio"
,"Panettiere"
,"Barbiere"
,"Pescatore"
,"Servitore"
,"Falegname"
,"Pastore di capre"
,"Tessitore"
,"Muratore"
,"Pellaio"
,"Servitore"
,"Tappezziere"
,"Carradore"
,"Sarto"
,"Architetto"
,"Inventore"
,"Tessitore"
,"Carradore"
,"Servitore"
,"Calzolaio"
,"Falegname"
,"Impiegato"
,"Ricamatore"
,"Criminale"
,"Muratore"
,"Venditore"
,"Carpentiere navale"
,"Messaggero"
,"Esploratore"
,"Carpentiere"
,"Falegname"
,"Gondoliere"
,"Mercante"
,"Barbiere"
,"Cordaio"
,"Carpentiere"
,"Muratore"
,"Bottaio"
,"Autista"
,"Carradore"
,"Carpentiere"
,"Banchiere"
,"Panettiere"
,"Messaggero"
,"Carpentiere"
,"Tessitore"
,"Tesoriere"
,"Carpentiere navale"
,"Venditore"
,"Fabbro"
,"Tappezziere"
,"Inventore"
,"Inventore"
,"Carradore"
,"Bottaio"
,"Impiegato"
,"Ripara tetti"
,"Carradore"
,"Droghiere"
,"Guardia"
,"Pellaio"
,"Guardia"
,"Guardia"
,"Tintore"
,"Macellaio"
,"Panettiere"
,"Carpentiere"
,"Panettiere"
,"Scrivano"
,"Pescatore"
,"Sarto"
,"Cerusico"
,"Marinaio"
,"Panettiere"
,"Autista"
,"Droghiere"
,"Pellicciaio"
,"Criminale"
,"Criminale"
,"Mercante"
,"Gondoliere"
,"Guardia"
,"Tessitore"
,"Cortigiano"
,"Cordaio"
,"Esattore"
,"Bottaio"
,"Pescatore"
,"Pastore di capre"
,"Cordaio"
,"Calzolaio"
,"Gondoliere"
,"Carradore"
,"Coltivatore"
,"Calzolaio"
,"Muratore"
,"Mastro di chiavi"
,"Guardia"
,"Avvocato"
,"Idraulico"
,"Cordaio"
,"Tappezziere"
,"Bottaio"
,"Birraio"
,"Fabbro"
,"Sanguisuga"
,"Pescatore"
,"Inventore"
,"Coltivatore"
,"Guardia"
,"Servitore"
,"Cordaio"
,"Conciatore"
,"Autista"
,"Messaggero"
,"Mercante"
,"Sarto"
,"Criminale"
,"Tintore"
,"Birraio"
,"Ricamatore"
,"Birraio"
,"Impiegato"
,"Apicoltore"
,"Tintore"
,"Venditore"
,"Marinaio"
,"Gondoliere"
,"Cordaio"
,"Carpentiere navale"
,"Macellaio"
,"Carpentiere navale"
,"Messaggero"
,"Barbiere"
,"Venditore"
,"Conciatore"
,"Tessitore"
,"Tintore"
,"Compositore"
,"Panettiere"
,"Falegname"
,"Mercante"
,"Gondoliere"
,"Carpentiere"
,"Macellaio"
,"Guardia"
,"Droghiere"
,"Gondoliere"
,"Barbiere"
,"Sarto"
,"Ricamatore"
,"Diplomatico"
,"Sarto"
,"Pastore di capre"
,"Bottaio"
,"Tintore"
,"Calzolaio"
,"Servitore"
,"Accademico"
,"Messaggero"
,"Folgoratore"
,"Conciatore"
,"Muratore"
,"Pescatore"
,"Conciatore"
,"Carpentiere navale"
,"Ricamatore"
,"Carpentiere navale"
,"Bottaio"
,"Macellaio"
,"Guardia"
,"Pastore di capre"
,"Fabbro"
,"Bottaio"
,"Tintore"
,"Sceriffo"
,"Coltivatore"
,"Macellaio"
,"Macellaio"
,"Cordaio"
,"Venditore"
,"Fabbro"
,"Coltivatore"
,"Coltivatore"
,"Cordaio"
,"Impiegato"
,"Tintore"
,"Carpentiere navale"
,"Pescatore"
,"Cacciatore di taglie"
,"Macellaio"
,"Criminale"
,"Conciatore"
,"Carradore"
,"Calzolaio"
,"Carpentiere"
,"Conciatore"
,"Carpentiere"
,"Tintore"
,"Carradore"
,"Impiegato"
,"Pastore di capre"
,"Pastore di capre"
,"Messaggero"
,"Droghiere"
,"Ripara tetti"
,"Ripara tetti"
,"Tessitore"
,"Macellaio"
,"Tintore"
,"Coltivatore"
,"Birraio"
,"Conciatore"
,"Falegname"
,"Sarto"
,"Marinaio"
,"Orologiaio"
,"Ripara tetti"
,"Coltivatore"
,"Panettiere"
,"Sarto"
,"Impiegato"
,"Guardia"
,"Falegname"
,"Bottaio"
,"Inventore"
,"Pellaio"
,"Autista"
,"Tappezziere"
,"Autore"
,"Magistrato"
,"Muratore"
,"Funzionario"
,"Tappezziere"
,"Fabbro"
,"Conciatore"
,"Droghiere"
,"Venditore"
,"Servitore"
,"Carpentiere navale"
,"Ripara tetti"
,"Ripara tetti"
,"Autista"
,"Capitano"
,"Panettiere"
,"Birraio"
,"Marinaio"
,"Tessitore"
,"Pellaio"
,"Sarto"
,"Sarto"
,"Ripara tetti"
,"Gondoliere"
,"Mercante"
,"Marinaio"
,"Birraio"
,"Inventore"
,"Gioielliere"
,"Droghiere"
,"Marinaio"
,"Cordaio"
,"Falegname"
,"Ricamatore"
,"Guardiano di spiriti"
,"Messaggero"
,"Servitore"
,"Birraio"
,"Panettiere"
,"Calzolaio"
,"Venditore"
,"Venditore"
,"Fabbro"
,"Criminale"
,"Ricamatore"
,"Pastore di capre"
,"Venditore"
,"Barbiere"
,"Falegname"
,"Criminale"
,"Soldato"
,"Fabbro"
,"Marinaio"
,"Pescatore"
,"Conciatore"
,"Ripara tetti"
,"Ricamatore"
,"Muratore"
,"Pellaio"
,"Ricamatore"
,"Pellaio"
,"Inventore"
,"Tessitore"
,"Gondoliere"
,"Falegname"
,"Ripara tetti"
,"Inventore"
,"Guardarotaie"
,"Macellaio"
,"Droghiere"
,"Servitore"
,"Mercante"
,"Droghiere"
,"Barbiere"
,"Autista"
,"Birraio"
,"Tappezziere"
,"Impiegato"
,"Inventore"
,"Droghiere"
,"Coltivatore"
,"Pescatore"
,"Autista"
,"Bottaio"
,"Pescatore"
,"Guardia"
,"Carpentiere navale"
,"Pastore di capre"
,"Sarto"
,"Tappezziere"
,"Autista"
,"Giornalista"
,"Conciatore"
,"Marinaio"
,"Bottaio"
,"Sussurro"
]
,"Tratti":[
"Ossessivo"
,"Sospettoso"
,"Calcolatore"
,"Crudele"
,"Incantevole"
,"Lunatico"
,"Candido"
,"Paranoico"
,"Enigmatico"
,"Accorto"
,"Sofisticato"
,"Sprezzante"
,"Cooperativo"
,"Malinconico"
,"Spavaldo"
,"Disonesto"
,"Reticente"
,"Elitario"
,"Agguerrito"
,"Vanitoso"
,"Audace"
,"Subdolo"
,"Sicuro di sé"
,"Cortese"
,"Paziente"
,"Arrogante"
,"Volatile"
,"Freddo"
,"Crudele"
,"Entusiasta"
,"Perspicace"
,"Cavaliere"
,"Tranquillo"
,"Noncurante"
,"Avventato"
,"Calmo"
]
,"Interessi":[
"Buon whisky, vino, birra"
,"La signora del pianto, beneficienza"
,"Filosofia naturale"
,"Combattimenti, duelli"
,"Esplorazioni, avventure"
,"Alchimia, medicina"
,"Amanti, romanticismo, tresche"
,"Storie sui demoni, leggende"
,"Bei vestiti, gioielli, pellicce"
,"Leggende pre-cataclisma"
,"Cucinare, giardinaggio"
,"Feste, eventi sociali"
,"Sentiero degli echi"
,"Poesia, novelle, scrittura"
,"Droghe, essenze, tabacco"
,"Cavalli, cavalcare"
,"Antichità, artefatti, curiosità"
,"Gadgets, nuove tecnologie"
,"Storia, leggende"
,"Belle arti, opera, teatro"
,"Architettura, arredamenti"
,"Libri arcani, rituali"
,"Navi, nautica"
,"Collezionista di armi"
,"Artigianato (pellame, ecc.)"
,"Dei dimenticati"
,"Musica, strumenti, danza"
,"Animali (uccelli,cani, gatti)"
,"Caccia, tiro a segno"
,"Essenze, alchimia"
,"Quadri, dipinti, sculture"
,"Chiesa dell'Estasi"
,"Spettrologia, elettroplasma"
,"Buon cibo, ristoranti"
,"Gioco d'azzardo, carte, dadi"
,"Politica, giornalismo"
]
,"Particolari":[
"Rivoluzionario. Complotta contro l'imperium."
,"Ciecamente fedele a un ideale, gruppo, o tradizione."
,"Recluso. Preferisce interagire tramite messaggeri."
,"In prigione o sotto l'arresto di una nobile casata."
,"Reputazione scandalosa (meritata o meno)."
,"Si preoccupa del suo aspetto, pettegolezzi, i suoi pari."
,"Orgoglioso del retaggio, tradizioni, lingua nativa."
,"Fanno affidamento al consiglio per prendere decisioni."
,"Superstizioso. Crede nei segni, numeri magici."
,"Ricoprono il loro ruolo grazie al ricatto."
,"Carica ereditaria. Forse non la meritano/desiderano."
,"Un simulacro riformato. Immune agli spiriti"
,"Celebrità. Reso popolare dalla stampa /musica / teatro."
,"Ha un diario dettagliato, appunti, archivi, registri."
,"Devoto alla famiglia."
,"Abusa di droghe/alchol. Spesso debilitato dai vizi."
,"Navigato. Conoscenze fuori da Duskwall."
,"Coinvolto in crimini di guerra dalla guerra dell'unità."
,"Usa la sua carica per spiare per un'altra fazione."
,"Debiti enormi (alle banche / criminali / famiglia)"
,"Ha una malattia cronica e richiede cure continue."
,"Controllato in segreto (o no?) da uno spirito possessore."
,"Circondato da adulatori, supplicanti, tirapiedi."
,"Pecora nera/reietto da una famiglia o organizzazione."
,"Non vede i difetti negli amici, alleati, famigliari, ecc."
,"Visionario. Ha idee radicali per il futuro."
,"Maledetto, tormentato, vessato da spiriti o demone."
,"Pregiudizi contro culture / convinzione / classe sociale."
,"Sposato in una famiglia importante/potente."
,"Impostore. Un aspetto importante è inventato."
,"Fermo tradizionalista. Si oppone a nuove idee."
,"Reputazione impeccabile. Altamente considerato."
,"Ampia educazione su ogni argomento accademico."
,"Ha una doppia vita grazie a un'identità segreta."
,"Intenso, fobia o odio irrazionale."
,"Aiuta i progetti di un demone (coscientemente o no)"
]
,"tratti di Tycheros":[
"Coda da demone"
,"Ombra in ritardo di mezzo secondo"
,"Ali da demone"
,"Pupille a taglio"
,"3 file di denti"
,"Escrescenze ossee"
,"Corna di pietra"
,"Fumo dagli occhi"
,"Occhi neri"
,"4 occhi"
,"Pelle di colore strano"
,"Articolazioni delle gambe invertite"
,"Tatuaggi blu cangianti"
]
}
,"Voci e altro":{
"Sentito a Duskwall":[
"Lyssa l'ha fatto con le sue mani, dicono. Occhio per occhio, a sangue freddo.<br />se davvero ha ucciso il suo capo, non è che un'infame? (sputa)... Ma non una che incrocerà presto."
,"Ho sentito che il nuovo ispettore era un comandante della cavalleria imperiale...?<br />suppongo che stanare delinquenti a dusk sia meglio che cacciare diavoli nelle terre morte, eh?"
,"Lo chiamo sangue rosso. Prendi veleno di rosposcarlatto, distillalo puro? un metodo sussuratomi da un demone, ahah! taglialo con una fiala diessenza di spirito frazionata, le memorie più belle di una vita passata; un macello da ottenere, ma con solo una goccia...<br />sì, sì come dicevo, lord scurlock ha...<br />lo sballo migliore per l'argento migliore, signoree signori."
,"Vedi, ci sono due tipi di persone a questo mondo io e il resto degli idioti."
,"Gli hai dato un pugno che l'ha fatto uscire dalle braghe!<br />erano già larghe, penso. Ha perso anche gli stivali. E poi sua moglie incinta mi si è lanciata contro. Cosa dovevo fare?"
,"Se ne va un altro corvo. Terribile!<br />cos'era? sette nell'ultima mezz'ora? nah, amico,questo è Crow's foot. Tipo, dove vengono adappollaiarsi, capisci? la notte è appena cominciata."
,"... Vista nello specchio.<br />tipo dietro di lui<br />no, solo il suo riflesso, nello specchio.<br />diavolo nero!"
,"Tally è scomparso dall'orfanotrofio. Ho chiesto alla preside se l'avesse preso qualcuno, mi ha cacciato fuori! sono disperata, non posso abbandonare così il mio fratellino!"
,"A me sembra un tatuaggio normalissimo.<br />ma no, vedi come si muove la chela del granchio? l'inchiostro è mescolato con sanguedi demone.<br />sì certo, e io sono la signora del pianto.<br />vedrai, vedrai. Una volta che si deposita bene..."
,"Ti ha minacciato? con cosa, una lama<br />ah, no, signor guardiano, niente di così comune, o non vi avrei chiamati. Lui, beh... è stato terribilmente bizzarro. Ha parlato con la voce del mio rickard, signore.<br />vi ha minacciato con un trucco di prestigio<br />non un trucco, signore! con la voce di rickard! e ha detto cose terribili.(sospira)<br />non è proprio un crimine, signora.<br />ma rickard è morto da sette anni! non è mai tornato da skovlan. Come faceva questo infame lampionario ad aver sentito la sua voce?"
,"Quel miserabile di rowley. Quella... Cosa è perversa. Ero fuori tardi l'altra sera e ti giuro che l'ho visto circondato da una dannata orda di feccia come lui. E gli stavano giurando fedeltà come se fosse il re del vicolo. Era come l'imitazione di una corte, con un trono e tutto. Sta formando un esercito, credimi!"
,"Sai perché ci si sbarazza dei corpi nei canali dopo la mezzanotte? gli spiriti degli annegati vivono qui. Beh, vivono? no? rivendicano tutto quello che tocca l'acqua al rintocco della mezzanotte. Tutto tranne quei gondolieri.<br />uhm-uhm e immagino tu abbia un amuletoda vendermi che mi terrà al sicuro...<br />che fortuna! guarda caso ho proprio..."
,"(canto marinaresco stonato)<br />ho venduto la mia terra per cacciare i Leviatan<br />ma la nave l'ho perduta, è laggiù nel nero mar!<br />ho remato fino a riva, come non lo vuoi sapere...<br />(più forte, aspettando il coro)<br />ma oste adesso portami un bicchiere!"        
]
,"Voci per le vie":[
"Qualcuno sta provando a creare un sindacato per i portuali."
,"Il sentiero degli echi compra bottiglie spettrali inabitate, nessuna domanda."
,"Un conestabile accetta mazzette per incastrare qualcuno per un crimine."
,"Le prostitute e le case di piacere sono state infiltrate dagli spettri."
,"La nuova droga, esca, viene fatta con il sangue di Leviatano e trasforma le persone in demoni."
,"Tutti i ricchi comprano i lucchetti di Turner, si dice siano impossibili da scassinare."
,"Il Ministero della Conservazione sta prendendo il controllo dei gondolieri."
,"Una nave da caccia di Leviatani è tornata senza superstiti e con un demone a bordo."
,"Un magistrato corrotto sta cercando vie d'uscita segrete da Duskwall, per sfuggire alle accuse."
,"La Chiesa dell'Estasi della Carne sta cercando un nuovo apice."
,"I guardiani di spiriti stanno facendo scorta di elettroplasma, in previsione di una carenza."
,"I caveau della banca di Charterhall sono stati svuotati, ma stanno insabbiando tutto."
]
,"Eventi della città nei giornali":[
"Epidemia"
,"Festival"
,"Incursioni"
,"Rivoluzione"
,"Incidente"
,"Disastro"
,"Rifugiati"
,"Sciopero"
,"Messa al bando"
,"Costruzione"
,"Assedio"
,"Beneficienza"
,"Demolizione"
,"Elezione"
,"Scandalo"
,"Legge"
,"Marziale"
,"Coscrizione"
,"Esodo"
,"Carestia"
,"Eccessi"
,"Scoperta"
,"Paranoia"
,"Assassinio"
,"Caccia alle streghe"
,"Parata"
,"Celebriazione"
,"Festività"
,"Rivolte"
,"Guerra tra bande"
,"Isteria"
,"Ondata di crimini"
,"Turbolenze"
,"Politiche"
,"Evasione"
,"Diplomazia"
,"Clima"
,"Soprannaturale"
,"Congregazione di culti"
]
,"Eventi degni di nota":[
"Strane nebbie plasmatiche<br />i corvi beccamorte rifuggono il distretto."
,"Le giubbe blu sospendono il pattugliamento delle strade. Campo libero al crimine!"
,"I cittadini si ribellano alle estorsioni reclutando bravi di altri distretti."
,"I canali si intasano di detriti, traboccanti di effluvi disgustosi."
,"Le baracche fatiscenti di drop in Crow's foot sono marchiate per la demolizione."
,"Canaglie evase da ironhook attraggono cacciatori di taglie in zona."
,"I guardiani di spiriti con i loro corvi hanno creato un appostamento nelle rovine del tempio."
,"Sono in atto perquisizioni dei blu in cerca di contrabbando o altro da confiscare."
,"Un talento locale (banda, chef, giocoliere) diventa popolare, aumenta la folla al mercato e nei negozi."
,"I canali del distretto vengono dragati per manuntenzione (o forse altri strani scopi.)"
,"Un fuoco divampante attraversa Crow's foot, minacciando di distruggere il distretto."
,"Un'antica cripta sotto il distretto, coperta di strani segni, viene rivelata attirando simulacri piangenti."
]
}    
,"Culto":{
"Dei dimenticati":[
"L'uno e i tanti"
,"Il fuoco argenteo"
,"L'accordo estatico"
,"La stella caduta"
,"Il signore del profondo"
,"La canzone muta"
,"La signora delle spine"
,"Il nostro sangue versato in gloria"
,"L'ariete"
,"Il ricettacolo vuoto"
,"L'occhio chiuso"
,"La mano dello sconforto"
,"L'affamato"
,"I cento volti"
,"La rete di dolore"
,"I pilastri della notte"
,"Il re arso"
,"Il padre dell'abisso"
,"La legione rinnegata"
,"Il sole invitto"
,"La rivelazione"
,"Il mondo radiante"
,"La regina ammantata"
,"Il riconciliatore"
,"La nuvola dell'afflizione"
,"Il circolo infranto"
,"Il conquistatore"
,"Lei che vince nell'Oscurità"
,"Il sogno oltre la morte"
,"La marea oscurata dal sangue"
,"I guardiani dei cancelli"
,"La bocca del vuoto"
,"Il custode della fiamma"
,"Il trono del giudizio"
,"La corona perduta"
,"Il cervo dorato"
]
,"Pratiche del culto":[
"Sacrificio: dati in pasto a bestie consacrate / dilaniati (mangiati?) da cultisti in frenesia."
,"Sacrificio: fatti scontrare con un campione consacrato in un'arena alla morte."
,"Sacrificio: ritualmente dissanguati sull'altare."
,"Sacrificio: overdose da dosi progressive di droghe piscotrope."
,"Sacrificio: ritualmente uccisi e rivendicati come campioni-spirito consacrati."
,"Sacrificio: immolati con mezzi arcani (fulminati, spirito infranto, maledizione letale)."
,"Congregazione: un'orgia di piacere (sesso, piaceri, danza, musica) e/o dolore."
,"Congregazione: inni sacri e preghiere per giorni senza sosta."
,"Congregazione: occupazione di un nexus sacro durante una convergenza astronomica."
,"Congregazione: un pellegrinaggio a un luogo sacro o creatura nelle terre morte / mare."
,"Congregazione: visione di gruppo / missione-sogno da essenza, droghe, o meditazione."
,"Congregazione: una rievocazione / pantomima di un evento sacro."
,"Acquisizione: una collezione di occhi / cuori / sangue di mistici o demoni."
,"Acquisizione: le schegge di un oggetto sacro distrutto (gioiello, spada, teschio, pietra)."
,"Acquisizione: gli scritti sacri originali di un profeta / maestro / santo."
,"Acquisizione: parti del corpo amputate (teste, mani, lingue) di eretici o apostati."
,"Acquisizione: proprietà allineate a geometrie sacre o armonizzate da eventi mistici."
,"Acquisizione: i fantasmi di profeti / mistici / fondatori / nemici dell'ordine."
,"Distruzione: rogo rituale di oggetti sacri (scritti runici, effigi, pelle, capelli)."
,"Distruzione: eradicazione rituale di uno spirito o demone."
,"Distruzione: la rottura di uno dei sigilli che impedisce al dio di scendere in terra."
,"Distruzione: distruzione di oggetti rituali / altari / templi sacri per un altro ordine."
,"Distruzione: eradicazione di armi / oggetti / siti / rituali che possono fermare il dio."
,"Distruzione: eradicazione di elementi sociali / legali / culturali che minacciano l'ordine."
,"Consacrazione: purificazione in un bagno di liquido sacro (sangue, vino, latte, oli, ecc.)."
,"Consacrazione: purificazione dei cancelli che consentono il passaggio del dio nel mondo."
,"Consacrazione: battesimo / benedizione di un accolito o oggetto in un pozzo spiritico."
,"Consacrazione: purifica / benedici cultisti con tatuaggi / scarnificazioni / mutilazioni."
,"Consacrazione: creazione di un idolo / opera d'arte / spazio rituale/ artefatto benedetto."
,"Consacrazione: anatema / runa / spiriti legati per bandire i nemici dell'ordine."
,"Dissacrazione: svilimento o profanazione di chi si è votato a un ordine nemico."
,"Dissacrazione: corrompere un luogo / oggetto / rituale / tradizione per ottenerne il potere."
,"Dissacrazione: profanare un luogo / oggetto / rituale per umiliare un altro ordine."
,"Dissacrazione: manipolare Autorità / istituzioni tper ottenerne il potere."
,"Dissacrazione: corruzione degli accoliti per prepararli alla loro trasformazione."
,"Dissacrazione: caos cieco e insensato; raccogliere i frutti dell'anarchia."
]
}
, "Tempo atmosferico":
{
"Tempo1":[
"Pioviggine"
,"Pioggia"
,"Pioggia"
,"Pioggia"
,"Pioggia battente"
,"Pioviggine"
,"Pioggia"
,"Pioggia battente"
,"Rovescio"
,"Nubifragio"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Estremo"
]
,"Tempo2":[
"Pioviggine"
,"Pioggia"
,"Pioggia battente"
,"Pioviggine"
,"Pioggia"
,"Pioggia"
,"Pioggia"
,"Pioggia battente"
,"Rovescio"
,"Nubifragio"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Nuvoloso"
,"Ventoso"
,"Nebbioso"
,"'sereno'"
,"Estremo"
]
, "Estremi":[
"Neve"
,"Ghiaccio"
,"Tempesta di fulmini"
,"Grandine"
,"Incredibilmente afoso"
,"Incredibilmente caldo secco"
,"Tempesta di neve"
,"Luna gemellee"
,"Secca???"
,"Senza luna"
, "La barriera visibile"
]
, "Conseguenze":[
"I canali esondano (sgorghi? acqua alta?)"
,"Si fermano le attività"
,"La barriera si rompe"
,"Incendio"
,"Fulmini orizzontali"
,"Allagamenti"
,"Il tetto perde acqua"
,"Qualcosa riemerge nel fiume"
]
}
}
const rawDataHit = {
"Bande":
{
"Assassini":[
"Due casate nobiliari in faida tra loro cercano degli assassini per un lavoro."
,"Una casata nobiliare in declino vuole vendicarsi dei suoi nemici."
,"Un lord o una lady in lutto cerca vendetta per il figlio morto in un duello legale."
,"Un nobile vuole eliminare il capitano e cacciatore di Leviatani suo rivale prima della prossima caccia."
,"Un nobile vuole aprirsi la strada verso un matrimonio di convenienza, facendo uccidere il corteggiatore suo rivale."
,"Un nobile è stato preso di mira da una fazione malavitosa e pagherà un'enormità di soldi per eliminare il leader della gang; con poca comprensione delle conseguenze."
,"Un boss criminale sta affrontando delle accuse molto serie e l'ispettore non può essere corrotto, uccidete i testimoni."
,"Il nuovo funzionario della città sta richiedendo forti tangenti per chiudere un occhio. è più conveniente ucciderlo. Ricevete numerose offerte per questo lavoro, da altrettante gang."
,"Tre gang da strada, tra loro in guerra, cercano degli assassini da ingaggiare."
,"Un potente boss mafioso si sta godendo la sicurezza della prigione che controlla. Il suo rivale vuole che entriate e lo facciate uscire di là."
,"L'ultimo/a sopravvissuto/a di una fazione mafiosa distrutta cerca vendetta."
,"Una fazione criminale è fuggita con il bottino. Trovateli e uccideteli, fate di loro un esempio per gli altri."
,"Due compagnie mercantili rivali stanno cercando qualcuno che assassini la rispettiva concorrenza."
,"Una spia ha identificato un ufficiale importante di Duskwall la cui morte potrebbe giovare la causa di alcuni interessi stranieri."
,"Un culto richiede una serie di specifici e bizzarri omicidi per un loro rituale oscuro."
,"Un amante col cuore spezzato vuole morti il suo ex e la sua nuova fiamma."
,"Un gruppo di povere famiglie ti offre l'insieme dei loro risparmi per uccidere il crudele capo di un ospizio per i poveri."
,"Un fantasma stranamente lucido ti guiderà dal suo omicida per ottenere vendetta; e successivamente a un tesoro nascosto come pagamento. "            
]
,"Avvoltoi":[
"I vostri clienti più prestigiosi sono stanchi di venire nel vostro territorio per una dose. Create una vetrina in una parte più onesta della città (o al contrario per i clienti di classe sociale inferiore)."
,"Il culto di un dio dimenticato vi fa un'offerta per una collaborazione: possono rendere il vostro prodotto più appetibile in cambio di... Un trattamento speciale."
,"Una nobile dilettante sempre sulla cresta dell'onda sta bazzicando nella vostra area con il suo entourage di leccapiedi, in cerca della 'prossima hit' da provare."
,"Un ardente predicatore fa proclami contro il vostro prodotto per le strade, abbassando la richiesta. Ma vi sembra di riconoscerlo come un vostro cliente..."
,"La gang che operava sul vostro territorio anni fa è tornata dalle isole del pugnale e si aspetta di tornare ai suoi affari come se nulla fosse."
,"Inizia ad apparire nelle strade un'imitazione del vostro prodotto, a un prezzo ribassato. Il vostro fornitore vi sta tagliando fuori."
,"I trafficanti vogliono eliminare tutti gli intermediari nella filiera e gestire le cose direttamente con voi."
,"I fantasmi dei vostri 'ex' clienti sono improvvisamente richiamati a voi, smaniosi per la loro dose."
,"Una famigerata cacciatrice di Leviatani ha gusti che... Solitamente non soddisfate, ma è disposta a pagare davvero molto bene."
,"Una giubba blu ha ucciso il suo ultimo spacciatore per aver spinto troppo in lì il loro rapporto, e si rivolge alla banda come fonte alternativa."
,"Una brutale gang di feroci assassini ha ripulito il covo del vizio di un rivale. Ora vogliono che siate voi a occuparvi della gestione."
,"Una figura mascherata vi paga profumatamente per l'opportunità di uccidere uno dei vostri clienti abituali mentre è... Distratto."
,"Un assassino arcano sta bersagliando fruitori e spacciatori, lasciando simulacri a vagare per la città."
,"Un operatore solitario sta distribuendo una versione molto più popolare del vostro prodotto."
,"Un membro del consiglio cittadino sta mettendo al vaglio un divieto assoluto per un prodotto illecito; potrebbero farsi convincere a fare in modo che sia il vostro, mandando la domanda alle stelle."
,"Una nuova gang del vizio sta facendo delle mosse molto scaltre e intelligenti. Le voci dicono che siano guidati dal fantasma di un criminale leggendario."
,"Gli studenti dell'accademia di Duskwall hanno dimostrato interesse per la vostra merce, ma dovete consegnarla direttamente, superando la sicurezza gestita dalle giubbe blu."
,"Un leggendario truffatore e la sua banda stanno colpendo diversi magazzini. è stata messa una taglia sulle loro teste: riuscirete a rivendicarla" 
]
,"Bravi":[
"Un gioielliere ha aperto un negozio qui a fianco. Ha un mucchio di oggetti interessanti da sgraffignare."
,"Un mercante del luogo sta dicendo a tutti che non si fa spaventare dai bulli ed esorta altri a seguire il suo esempio. Le persone iniziano a dargli corda."
,"Un pescatore di canale vuole che le barche del suo concorrente vengano distrutte."
,"Il proprietario di una taverna deve far fronte a risse tumultuose ogni notte. Vuole che questa storia finisca."
,"Una distilleria licenzia tutti i lavoratori skovlanesi e si rifiuta di pagare loro il salario per il lavoro già svolto. Gli skov sono accampati lì fuori e chiedono giustizia."
,"Un gruppo di mercanti sta cercando carne da macello per sfidare una gang del luogo."
,"Le giubbe blu hanno allestito torri di guardia e posti di blocco per perquisire le persone in cerca di armi e gonfiare la quota di arresto giornaliera."
,"Il consiglio cittadino vuole dei gambizzatori per mettere fine ai moti sindacali tra i moli."
,"Un nobile ha assunto un piccolo esercito privato per proteggere la sua tenuta per ragioni sconosciute. Dev'esserci qualcosa che vale la pena difendere..."
,"I folgoratori stanno costruendo una rumorosa macchina metallica in una torre di fronte a un palazzo. I condomini sono indignati per il rumore e il fumo."
,"La prigione di ironhook ha indetto forti assunzioni per fornire sicurezza a una spedizione speciale nelle terre morte. I predoni sono tutti detenuti nel braccio della morte."
,"Soldati skovlanesi hanno rubato una nave da guerra armata e stanno assaltando altre navi nel canale."
,"Una gang rivale conserva i bottini dei loro crimini in bella vista nel loro covo, aspettandosi che la loro temibile reputazione dissuada da eventuali ladrocini."
,"e' comparso un gruppo di vigilanti che attacca chiunque ritenga essere \"Feccia criminale\"."
,"Una malvagia gang molesta il distretto, rubando impunemente e provocando chiunque a sfidarli."
,"Un'orda di simulacri vaga nei canali sotterranei, trascinando già le persone fino ad affogarle e terrorizzando la zona, costringendo negozi e covi del vizio alla chiusura."
,"Una bisca ha bisogno di una banda per fare un esempio di un forte scommettitore che non ha saldato un grosso debito."
,"Un cacciatore di vampiri è giunto a Duskwall e richiede assistenza."
]
,"Cultisti":[
"Uno studente dell'accademia di Duskwall pubblica un trattato dichiarando che la vostra divinità è la copia corrotta di un dio ancora più antico."
,"Sta diventando una moda tra i giovani dell'alta società quella di fingere di svenire e avere visioni, ma non tutte sono finte."
,"Dei lavori di costruzione hanno accidentalmente riportato alla luce un antico pozzo spiritico e risvegliato le entità intrappolate lì dentro fin dal cataclisma."
,"I paramenti segreti di un culto rivale hanno qualche legame con l'imperatore eterno: sono suoi emissari o è una mera coincidenza."
,"Un nobile ha eseguito un rituale nel disperato tentativo di cercare assistenza in una divinità. Siete stati scelti come strumenti per aiutarlo."
,"Un famoso collezionista di artefatti vomita sangue nero fino a morire soffocato in mezzo alla strada farfugliando il nome della vostra divinità."
,"Un culto rivale sta distruggendo qualsiasi artefatto e sito sacro di altre divinità. Sembra che abbiano qualche metodo arcano per scoprirli. Potreste essere i prossimi."
,"L'omicidio di un nobile porta con sé segni e sigilli della vostra divinità, lasciati in bella vista sulla scena del delitto."
,"I cittadini nell'area del vostro covo hanno iniziato a lavorare insieme in strani orari del giorno, in trance, costruendo qualcosa di alieno riutilizzando stravaganti detriti."
,"Una triade di distinti fantasmi arriva al vostro covo e dice di essere il vero antico nucleo di maestri del vostro culto."
,"Il campione consacrato di un culto rivale sfida il vostro prescelto in un combattimento mortale."
,"I guardiani di spiriti vogliono riportare in uso un antico atto barbarico e bruciare una strega in mezzo alla piazza. La vostra divinità ha vietato queste tradizioni, ora e per sempre."
,"Un tomo ammuffito è stato recuperato dalla borsa di un vagabondo tycherosiano: esso contraddice alcuni importanti principi della dottrina del vostro culto."
,"Un facoltoso culto vi offre ricchezze (denaro, rivendicazioni, cricche, ecc.) per abbandonare la vostra fede ed entrare nella loro congregazione."
,"Un cacciatore di Leviatani ritorna in porto, privo di equipaggio o di altri oggetti, salvo una cosa: un'enorme piramide di metallo alieno, che ronza il nome segreto del vostro dio."
,"Una cricca di teppisti sta avendo seri problemi di attacchi mistici da parte di un gruppo rivale. Vi vogliono assoldare per mettere fine a questa storia."
,"Delle monete benedette poste nella bocca di deceduti fedeli al culto permettono ai fantasmi di ritornare anche dopo il trattamento dei guardiani al crematorio. Chi sta facendo tutto ciò e come"
,"I vostri altari si sbriciolano, i vostri artefatti si spezzano. Dimostrate la vostra vera fede o disperatevi.   "
]
,"Ombre":[
"Un gallerista locale annuncia una mostra di rari gioielli antichi iruviani."
,"Il sentiero degli echi ha bisogno che trafughiate un corpo dal crematorio prima che venga dissolto."
,"Un collezionista vuole rubare un pezzo d'arte o di tecnologia e rimpiazzarlo con un falso."
,"Un cliente vuole salvare una persona amata dalla servitù forzata nell'ospizio dei poveri."
,"Un fantasma vuole che mettiate al sicuro tutta la sua collezione di oggetti terreni."
,"Un vecchio maestro assassino torna in attività per un'ultima commissione. Ci sono molti disposti a pagare profumatamente per sapere chi è il bersaglio."
,"La pecora nera di una famiglia nobiliare vuole la sua vendetta; gli atti di proprietà di una tenuta ancestrale sono la chiave."
,"Una gang di produttori di droga vuole ottenere la formula segreta del popolare nuovo prodotto dei rivali."
,"Sono stati recuperati strani artefatti dal mare vuoto. Sono custoditi al crematorio di bellweather per essere analizzati dai guardiani di spiriti."
,"Si vocifera di una possibile guerra, come sempre. Piazzate delle prove compromettenti nell'ufficio dell'ambasciatore."
,"Agenti anti-imperiali si stanno scambiando informazioni viaggiando in treno. Intercettate i loro comunicati."
,"Un professore della torre dei folgoratori vuole gli appunti di ricerca di un rivale. Fatelo sembrare un banale furto con scasso."
,"Una squadra di giubbe blu non vuole fare un arresto particolarmente rischioso. Rubate le prove dalla cassaforte dell'ispettore."
,"Le prove incriminanti nei confronti di un vulnerabile boss criminale sono custodite nel caveau fino al processo."
,"Un cliente cerca l'origine di testi alterati venduti all'accademia, che stanno portando gli studenti a una follia omicida."
,"Un ispettore ormai disperato ha bisogno che falsifichiate delle prove per incastrare un guardiano di spiriti corrotto da un demone."
,"C'è il circo in città, con una varietà di strani e misteriosi animali. Un cliente è disposto a pagare bene per un nuovo cucciolo."
,"Solo un membro della gang è sopravvissuto alla missione che hanno mandato all'aria. Riuscite a ripulire la scena prima che arrivino le Autorità."
]
,"Trafficanti":[
"Insurrezionisti skovlanesi necessitano di rifornimenti per la loro campagna di attacchi terroristici ai danni delle istituzioni cittadine."
,"Organizzatori sindacali vogliono armare una fabbrica in vista di uno sciopero."
,"Una terribile guerra tra gang crea una forte domanda di equipaggiamento militare non commerciale e artiglieria pesante."
,"Nobili esiliati intenti a spassarsela a Duskwall hanno un improvviso bisogno di tornare a casa con urgenza, non vogliono fornire spiegazioni."
,"Dei cacciatori di Leviatani fanno una sosta non registrata. Incontrateli fuori città e portate loro qualcosa senza che venga controllata."
,"Un'ereditiera deve fuggire per incontrare il suo amore perduto. Se lo fate sembrare un rapimento, dividerà il riscatto con voi."
,"Il consiglio cittadino mette fuori legge una merce prima lecita."
,"Un'evasione di massa dalla prigione di ironhook significa che molti prigionieri evasi cercano di fuggire dalla città."
,"Una giubba blu vi aiuterà ad acquisire un veicolo sequestrato a un'altra banda per una cifra nominale."
,"Una nuova spezia è stata 'scoperta' a tycheros, ma è ufficialmente bandita. Naturalmente, ora tutti la vogliono."
,"Un percorso di contrabbando è bloccato dalla guardia a causa di: collasso imminente - strani eventi - gas tossici - fuoco."
,"Un'organizzazione criminale necessita che delle armi raggiungano l'interno di ironhook per prenderne il controllo."
,"Dei cultisti vogliono esfiltrare il loro 'prescelto' toccato dai demoni verso le terre morte e senza destare i guardiani di spiriti."
,"Un antico artefatto è stato individuato oltre la barriera e alcuni accademici lo vogliono immediatamente. Per studiarlo, ovviamente."
,"Un distretto è in quarantena per una pestilenza o un'infestazione di spettri. C'è bisogno di generi di prima necessità e barriere spettrali."
,"Un cliente vuole che trasportiate uno strano pacco in giro per la città per due giorni. Non fermatevi mai, sarebbe spiacevole!"
,"Un treno deragliato nelle terre morte ha un sacco di mercanzia recuperabile. Magari anche sopravvissuti ricchi e grati."
,"Congelati i beni di un nobile per attività criminale. Al suo cacciaLeviatani, a pieno carico dopo una spedizione, viene impedito di attraccare.   "  
]
}
,"Il colpo": {
"Riassunto":
[`un bersaglio. Ministero della Conservazione.\n
un luogo. Uno dei magazzini per lo stoccaggio del contrabbando vicino alla stazione gaddoc.\n
una situazione. Una rete di contrabbando di essenza di spirito, proprio ieri, è stata beccata dai guardiani presso la stazione di gaddoc.\n
un vettore ovvio per il piano. Laroze può farsi assumere in nero come guardia privata. Vi farà entrare dal retro, per una fetta dei guadagni.\n
\n
informazioni più precise:\n
fazioni collegate e cosa vogliono o necessitano. Quell’essenza era stata pagata dall’alveare. Vogliono ciò che è loro.\n
un vettore non così scontato per il piano. Le essenze di spirito possono essere richiamate attraverso il campo spettrale... In teoria.\n
segreti interessanti, un collegamento a un’opportunità alternativa. è molto probabile che i guardiani mettano in sicurezza l’essenza catturata con protezioni arcane. I riconciliati aborrono lo scambio di essenza e potrebbero essere un potenziale alleato o nemico, a seconda di quello farete.\n`
],
"Cliente/bersaglio":[
"Nobile"
,"Ufficiale"
,"Banchiere"
,"Capitano"
,"Posseduto"
,"Simulacro"
,"Accademico"
,"Studioso"
,"Vampiro"
,"Altro non morto"
,"Sacerdote"
,"Cultista"
,"Dottore"
,"Alchimista"
,"Mercenario"
,"Teppista"
,"Rivoluzionario"
,"Rifugiato"
,"Spacciatore"
,"Fornitore"
,"Corriere"
,"Marinaio"
,"Spia"
,"Informatore"
,"Ricettatore"
,"Scommetitore"
,"Boss criminale"
,"Mercante"
,"Negoziante"
,"Fantasma di (tira ancora)"
,"Sussurro"
,"Cultista"
,"Trafficante"
,"Ladro"
,"Manovale"
,"Commerciante"
,"Artista"
,"Scrittore"
,"Magistrato"
,"Capo distretto"
,"Demone (mascherato)"
,"Collezionista occulto"
,"Conestabile"
,"Ispettore"            
],
"Lavoro":[
"Raccolta"
,"Piazzamento"
,"Impersona"
,"Depista"
,"Distruggi"
,"Deturpa"
,"Crea"
,"Rianima un simulacro"
,"Rapina"
,"Furto"
,"Rapina"
,"Rapina a mano armata"
,"Terrorizza"
,"Estorci"
,"Incursione"
,"Difesa"
,"Estrai essenza"
,"Trova"
,"Nascondi"
,"Piazza"
,"Rimuovi rune"
,"Avvelena"
,"Simula incidente"
,"Scorta"
,"Sicurezza"
,"Cerimonia / ferma un rituale"
,"Bandisci"
,"Evoca"
,"Pedinamento"
,"Sorveglianza"
,"Sabotaggio"
,"Dolo"
,"Sparizione"
,"Riscatto"
,"Ricatta"
,"Discredita"
,"Maledici"
,"Santifica"
,"Assasinio"
,"Contrabbando"
,"Corriere"
,"Truffa"
,"Spionaggio"
,"Negozia"
,"Minaccia"
],
"Modifica o complicazione":[
"Un elemento è una copertura perpratiche eretiche di un culto"
,"Il lavoro è un test per un lavoro successivo"
,"Il luogo si muove (il sito cambia, è su un veicolo, ecc.)"
,"Il lavoro richiede un viaggio in mare"
,"Il lavoro porta avanti gli interessi segruenti di un prestigioso mercante"
,"Il lavoro richiede di viaggiare in elettrotreno"
,"Il lavoro porta avanti gli interessi segreti di un vampiro"
,"Il luogo è usato da una gang pericolosa"
,"Il lavoro porta avanti gli interessi segreti di un boss criminale"
,"Un elemento è un facciata per un'impresa criminale"
,"Il lavoro porta avanti gli interessi segreti di un ufficiale cittadino"
,"Il lavoro porta avanti gli interessi segreti di un demone"
,"Bisogna visitare le terre morte"
,"Il lavoro porta avanti gli interessi segreti di un rivoluzionario"
,"Spiriti impazziti posseggono alcuni/molti/tutti o coinvolti"
,"Un occultista ha previsto il colpo e ha avvertito le parti interessate"
,"Spiriti impazziti infestano il luogo"
,"Il lavoro è una trappola impostata dai vostri nemici"
],
"Legato a una persona":[
"Strano fantasma, demone, dio"
,"amico di un Pg"
,"rivale di un Pg"
,"fornitore del vizio di un Pg"
,"città volto noto di Duskwall"
,"Banda contatto"
],
"E fazioni":[
"Ulf ironborn"
,"Marinai o portuali"
,"Cacciatori di Leviatani"
,"Lord scurlock"
,"Ministero della Conservazione"
,"Il consiglio o lafondazione"
,"Rifugiati skovlanesi"
,"Gli dei dimenticati"
,"Folgoratori"
,"Esercito imperiale"
,"Guardarotaie o la brigata"
,"Un consolato"
,"Le giubbe grigie"
,"Gli spettri"
,"Le fioche sorelle"
,"Sentiero o riconciliati"
,"Messi o gazzettini"
,"La Chiesa dell'Estasi"
,"Predoni delle terre morte"
,"Giubbe blu o ispettori"
,"Guardiani dispiriti"
,"Le fusciacche rosse"
,"Il circolo della fiamma"
,"Le roncole"
,"La signoradel pianto"
,"I corvi"
,"I perduti"
,"I lampionari"
,"I segugi della nebbia"
,"Prigione di ironhook"
,"Tritasangue"
,"Operai o servitori"
,"L'alveare"
,"Gondolieri o nocchieri"
]
}
}
