const rawData = {
"Demone":{
    "Nome":[
    "Sevraxis"
    ,"Korvaeth"
    ,"Azarax"
    ,"Kylastra"
    ,"Oryxus"
    ,"Zalvroxos"
    ,"Ahazu"
    ,"Arkeveron"
    ,"Vaskari"
    ,"Ixis"
    ,"Esketra"
    ,"Kyronax"
    ,"Argaz"
    ,"Voldranai"
    ,"Ardranax"
    ,"Kethtera"
    ,"Tyraxis"]
    ,"aspetto1":[
        "Protusioni ossee"
    ,"Icore gocciolante"
    ,"Occhi o marchiature ardenti"
    ,"Liquidi gelano, bollono, diventano sangue o cenere"
    ,"Capelli o pelliccia"
    ,"Piume"
    ,"Ali di cuoio"
    ,"Scaglie (onice, iridescenti, cristalline, metalliche, ecc.)"
    ,"(ondeggiano come sott?acqua, bruciano di fiamma freddo, ecc.)"
    ,"Le piante avvizziscono o fioriscono"
    ,"Luci fioche o bagliori"
    ,"Numerose braccia"
    ,"Ingranaggi si fermano"
    ,"Tanti occhi"
    ,"Coda a frustra"
    ,"Artigli affilati"
    ,"Tentacoli"
    ,"Occhi da squalo"
    ,"Spine"
    ,"Guscio duro, placche metalliche"
]
    ,"Tratti":[
    "Sfrontato"
    ,"Rivelatorio"
    ,"Competente"
    ,"Folle"
    ,"Vendicativo"
    ,"Perspicace"
    ,"Inqusitorio"
    ,"Bizzarro"
    ,"Curioso"
    ,"Territoriale"
    ,"Educativo"
    ,"Volatile"
    ,"Suscettibile"
    ,"Insistente"
    ,"Affascinante"
    ,"Guida"
    ,"Aggressivo"
    ,"Profetico"
    ,"Dominante"
    ,"Arrabbiato"
    ,"Violento"
    ,"Astuto"
    ,"Reattivo"
    ,"Caotico"
    ,"Ingannevole"
    ,"Distruttivo"
    ,"Geloso"
    ,"Vile"
    ,"Esigente"
    ,"Pazzo"
    ,"Isterico"
    ,"Vero"
    ,"Selvaggio"
    ,"Crudele"
    ,"Fugace"
    ,"Disperato"
]
    ,"Effetti secondari":[
    "Strane ombre"
    ,"Vento di tempesta"
    ,"Voci nella testa"
    ,"Vento rapido"
    ,"Brina, Gelo"
    ,"Suoni tempestosi"
    ,"Foschia, Nebbia"
    ,"Vento"
    ,"Echi visivi intensi"
    ,"Scarica"
    ,"Elettrica"
    ,"Freddo"
    ,"Fulmini"
    ,"Buio completo"
    ,"Ombre avvolgenti"
    ,"Ombre inquietanti"
    ,"Nebbia gelante"
    ,"Tenui echi"
    ,"Magnetismo intenso"
    ,"Tenui visioni del passato"
]
    ,"aspetto2":[
    "caratteristiche Elementali"
    ,"Mostruoso"
    ,"Umanoide"
    ,"Animale"
    ,"caratteristiche Bestiali"
    ,"Amorfo"
]
    ,"affinità":[
    "Tempesta, Vento"
    ,"Cielo, Stelle"
    ,"Mare, Acqua"
    ,"Terra, Metallo"
    ,"Fuoco, Fumo"
    ,"Oscurità"
]
    ,"desiderio":[
    "Sofferenza"
    ,"Vendetta"
    ,"Caos"
    ,"Manipolazione"
    ,"Controllo"
    ,"Corruzione"
    ,"Guerra"
    ,"Delirio"
    ,"Potere"
    ,"Omicidio"
    ,"Brutalità"
    ,"Conoscenza"
    ,"Libertà"
    ,"Successo"
    ,"Paura"
    ,"Giustizia"
    ,"Inganno"
    ,"Piacere"
]
    ,"Orrori Evocati":[
    "Essere Metallico"
    ,"Nuvola di cenere ardente"
    ,"Geometria Impossibile"
    ,"Globo Divorante"
    ,"Animale Mostruoso"
    ,"Brandelli di Carne"
    ,"Viscere Pulsanti"
    ,"Pietra Animata"
    ,"Essere Liquido"
    ,"Scheletro di Vetro Nero"
    ,"Sfere Scintillanti"
    ,"Artigli Sferzanti"
    ,"Cefalopode Fluttuante"
    ,"Vibrazioni Tremolanti"
    ,"Rocchetto di Spine"
    ,"Luci Ipnotiche"
    ,"Essere Scuoiato"
    ,"Serpiforme"
    ,"Essere Fiammeggiante"
    ,"Oscurità Asfissiante"
    ,"Pianta infestante"
    ,"Essere d'Ombra"
    ,"Ingranaggi Contorti"
    ,"Muco Vorticante"
    ,"Foschia Psichica"
    ,"Massa Informe"
    ,"Catrame Putrido"
    ,"Fuoco Freddo"
    ,"Nube Tossica"
    ,"Argento Vivo"
    ,"Vapori Nauseabondi"
    ,"Schegge Cristalline"
    ,"Bava Viscida"
    ,"Sciame di Insetti"
    ,"Insettoide"
    ,"Essere Radiante"
]
}
,"Edifici":{
"materiale":[
,"Grigio"
,"Mattone"
,"Blocchi di Pietra"
,"Intonaco e Legno"
,"Lamiera"
,"Assi di Legno"
,"Pietra e Legno"
]
,"dettagli1":[
"Lavorazioni della Pietra"
,"Lavorazioni del Legno"
,"Giardino"
,"Ferro Battuto"
,"Piastrelle"
,"Lavorazioni di Vetro"
]
,"Uso":[
"Laboaratorio"
,"Magazzino"
,"Bagno Pubblico"
,"Grotta"
,"Stazione di Guardia"
,"Grotta"
,"Fabbrica"
,"Bagno Pubblico"
,"Birrificio"
,"Appartamenti"
,"Fabbrica"
,"Piccola Casa"
,"Molo"
,"Bordello"
,"Sartoria"
,"Ospizio"
,"Birrificio"
,"Appartamenti"
,"Bordello"
,"Caffà"
,"Giardino di Funghi"
,"Macellaio"
,"Tatuatore"
,"Magazzino"
,"Case Popolari"
,"Magazzino"
,"Giardino di Funghi"
,"Raffineria"
,"Arene da Combattimento"
,"Piazza, Fontana"
,"Fabbrica"
,"Laboaratorio"
,"Bordello"
,"Taverna"
,"Altare"
,"Appartamenti"
,"Appartamenti"
,"Bisca"
,"Molo"
,"Sartoria"
,"Taverna"
,"Panettiere"
,"Cerusico"
,"Fabbrica"
,"Altare"
,"Speziale"
,"Tatuatore"
,"Case a Schiera"
,"Fucina"
,"Molo"
,"Raffineria"
,"Giardino di Funghi"
,"Piccola Casa"
,"Allevamento di Anguille"
,"Fabbrica"
,"Centrale Energetica"
,"Laboaratorio"
,"Macellaio"
,"Stalle per Capre"
,"Sartoria"
,"Ospizio"
,"Mercato"
,"Tribunale, Galera"
,"Arene da Combattimento"
,"Case a Schiera"
,"Tatuatore"
,"Bordello"
,"Fucina"
,"Grotta"
,"Allevamento di Anguille"
,"Grotta"
,"Vinaio"
,"Piccola Casa"
,"Fucina"
,"Rovina"
,"Locanda"
,"Cerusico"
,"Piazza, Fontana"
,"Raffineria"
,"Allevamento di Anguille"
,"Panettiere"
,"Rovina"
,"Altare"
,"Macellaio"
,"Fucina"
,"Maestro Artigiano"
,"Bordello"
,"Mercato"
,"Cerusico"
,"Altare"
,"Bagno Pubblico"
,"Allevamento di Anguille"
,"Panettiere"
,"Fabbrica"
,"Covo di Tossici"
,"Bagno Pubblico"
,"Panettiere"
,"Laboaratorio"
,"Giardino di Funghi"
,"Tribunale, Galera"
,"Bordello"
,"Ospizio"
,"Cisterna"
,"Stalle per Capre"
,"Mercato"
,"Gioielliere"
,"Tribunale, Galera"
,"Giardino di Funghi"
,"Bisca"
,"Stalle per Capre"
,"Grotta"
,"Galleria d'Arte"
,"Molo"
,"Stazione di Guardia"
,"Piazza, Fontana"
,"Appartamenti"
,"Spiritualista"
,"Panettiere"
,"Giardino Radiante"
,"Mercato"
,"Stazione di Guardia"
,"Bagno Pubblico"
,"Panettiere"
,"Stazione di Guardia"
,"Birrificio"
,"Ospizio"
,"Raffineria"
,"Cerusico"
,"Mercato"
,"Raffineria"
,"Birrificio"
,"Magazzino"
,"Bordello"
,"Macellaio"
,"Taverna"
,"Cerusico"
,"Tatuatore"
,"Birrificio"
,"Bagno Pubblico"
,"Piazza, Fontana"
,"Rovina"
,"Altare"
,"Giardino di Funghi"
,"Locanda"
,"Covo di Tossici"
,"Altare"
,"Bisca"
,"Covo di Tossici"
,"Fucina"
,"Locanda"
,"Cerusico"
,"Tribunale, Galera"
,"Mercato"
,"Aia"
,"Parco"
,"Birrificio"
,"Covo di Tossici"
,"Sartoria"
,"Macellaio"
,"Stalle per Capre"
,"Aia"
,"Fucina"
,"Sartoria"
,"Case Popolari"
,"Bisca"
,"Macellaio"
,"Covo di Tossici"
,"Magazzino"
,"Grotta"
,"Merceria"
,"Tatuatore"
,"Piazza, Fontana"
,"Piazza, Fontana"
,"Case a Schiera"
,"Allevamento di Anguille"
,"Tabaccaio"
,"Covo di Tossici"
,"Mercato"
,"Monumento"
,"Case Popolari"
,"Sartoria"
,"Piccola Casa"
,"Macellaio"
,"Locanda"
,"Cerusico"
,"Accademia"
,"Molo"
,"Raffineria"
,"Bisca"
,"Molo"
,"Allevamento di Anguille"
,"Bisca"
,"Ristorante"
,"Giardino di Funghi"
,"Taverna"
,"Magazzino"
,"Cerusico"
,"Ospizio"
,"Stalle per Capre"
,"Tempio"
,"Rovina"
,"Aia"
,"Tatuatore"
,"Fabbrica"
,"Mercato"
,"Case Popolari"
,"Locanda"
,"Arene da Combattimento"
,"Bar, Lounge"
,"Bagno Pubblico"
,"Baracca"
,"Rovina"
,"Case a Schiera"
,"Arene da Combattimento"
,"Covo di Tossici"
,"Sartoria"
,"Piccola Casa"
,"Teatro"
,"Grotta"
,"Estetista"
,"Magazzino"
,"Macellaio"
,"Raffineria"
,"Panettiere"
,"Allevamento di Anguille"
,"Taverna"
,"Sartoria"
,"Locanda"
,"Ospizio"
,"Teatro Lirico"
,"Fabbrica"
,"Fucina"
,"Mercato"
,"Laboaratorio"
,"Baracca"
,"Ospizio"
,"Ospizio"
,"Rovina"
,"Raffineria"
,"Birrificio"
,"Stazione di Guardia"
,"Allevamento di Anguille"
,"Taverna"
,"Case Popolari"
,"Stalle per Capre"
,"Tribunale, Galera"
,"Arene da Combattimento"
,"Altare"
,"Bordello"
,"Stalle per Capre"
,"Cerusico"
,"Bagno Pubblico"
,"Bordello"
,"Stalle per Capre"
,"Baracca"
,"Rovina"
,"Piazza, Fontana"
,"Locanda"
,"Case Popolari"
,"Stazione di Guardia"
,"Ospizio"
,"Case a Schiera"
,"Baracca"
,"Arene da Combattimento"
,"Arene da Combattimento"
,"Piccola Casa"
,"Stazione di Guardia"
,"Banca"
,"Taverna"
,"Bordello"
,"Tribunale, Galera"
,"Arene da Combattimento"
,"Laboaratorio"
,"Giardino di Funghi"
,"Villa"
,"Stalle per Capre"
,"Ospizio"
,"Bisca"
,"Bagno Pubblico"
,"Bisca"
,"Molo"
,"Laboaratorio"
,"Appartamenti"
,"Tatuatore"
,"Tatuatore"
,"Allevamento di Anguille"
,"Aia"
,"Aia"
,"Fabbrica"
,"Covo di Tossici"
,"Tribunale, Galera"
,"Laboaratorio"
,"Tribunale, Galera"
,"Case a Schiera"
,"Panettiere"
,"Stazione di Guardia"
,"Negozio di libri"
,"Appartamenti"
,"Locanda"
,"Bisca"
,"Baracca"
,"Aia"
,"Casa Padronale"
,"Aia"
,"Piccola Casa"
,"Macellaio"
,"Giardino di Funghi"
,"Distilleria"
,"Aia"
,"Stazione di Guardia"
,"Fabbrica"
,"Piazza, Fontana"
,"Taverna"
,"Appartamenti"
,"Covo di Tossici"
,"Piccola Casa"
,"Tatuatore"
,"Aia"
,"Mercato"
,"Baracca"
,"Case Popolari"
,"Piazza, Fontana"
,"Case a Schiera"
,"Appartamenti"
,"Piccola Casa"
,"Molo"
,"Locanda"
,"Arene da Combattimento"
,"Stalle"
,"Case a Schiera"
,"Rovina"
,"Bisca"
,"Aia"
,"Grotta"
,"Taverna"
,"Altare"
,"Rovina"
,"Locanda"
,"Case a Schiera"
,"Fucina"
,"Bagno Pubblico"
,"Covo di Tossici"
,"Baracca"
,"Raffineria"
,"Fucina"
,"Fucina"
,"Arene da Combattimento"
,"Allevamento di Anguille"
,"Alchimista"
,"Panettiere"
,"Grotta"
,"Altare"
,"Tribunale, Galera"
,"Case Popolari"
,"Baracca"
,"Tatuatore"
,"Panettiere"
,"Sartoria"
,"Birrificio"
,"Stalle per Capre"
,"Tribunale, Galera"
,"Case Popolari"
,"Magazzino"
,"Casa Galleggiante"
,"Magazzino"
,"Grotta"
,"Appartamenti"
,"Laboaratorio"
,"Piccola Casa"
,"Laboaratorio"
,"Molo"
,"Molo"
,"Appartamenti"
,"Mercato"
,"Sartoria"
,"Giardino di Funghi"
,"Case a Schiera"
,"Altare"
,"Case Popolari"
,"Raffineria"
,"Baracca"
,"Macellaio"
,"Taverna"
,"Archivio"
,"Magazzino"
,"Piazza, Fontana"
,"Birrificio"
,"Fiorista"
,"Rovina"
,"Baracca"
,"Stazione di Guardia"
,"Clinica"
,"Residenza"
,"Stazione di Guardia"
,"Cerusico"
,"Birrificio"
]
,"Dettagli2":[
"Sacrario, Altare"
,"Polvere, Detriti"
,"Finestre Blindate"
,"Percorsi Panoramici"
,"Arredamento Utilitaristico"
,"Acqua Gocciolante"
,"Lucerne Fumose"
,"Luci Elettriche Crepitanti"
,"Meccanismo Ticchettante"
,"Basso, Angusto"
,"Rifiniture Eleganti"
,"Accogliente, Caldo"
,"Scala a Chiocciola, Scaletta"
,"Tappezzerie, Quadri"
,"Porte Segrete"
,"Austerità Spartana"
,"Usura, Danni"
,"Fuochi Scoppiettanti"
,"Cantine"
,"Robusto, Tranquillo"
,"Balconi"
,"Logoro, Consumato"
,"Pavimento Scricchiolante"
,"Piante, Fiori"
,"Tende Pesanti, Tappeti Spessi"
,"Arredi di Antiquariato"
,"Spifferi, Freddo"
,"Ammasso di Curiosità"
,"Barriere Spiritiche, Vecchie Rune"
,"Traballante, Sgangherato"
,"A Volta, Spazioso"
,"Passerelle"
,"Rigoglioso, Comodo"
,"Ruvida Essenzialità"
,"Artefatti Bizzarri"
,"Strani Arnesi"
]
,"oggetti1":[
"Sedie"
,"Diagrammi"
,"Mappe"
,"Librerie"
,"Orologio"
,"Scrivania"
,"Scrivania"
,"Libri"
,"Quaderni"
,"Cartigli"
,"Armadio"
,"Documenti"
,"Calamaio"
,"Scaffali"
,"Lampada"
,"Grafici"
,"Lavagna"
,"Tavolo"
]
,"oggetti2":[
"Divano"
,"Letto"
,"Poltrone"
,"Carillion"
,"Baule"
,"Tavolo"
,"Brocca"
,"Drappeggi"
,"Lampade"
,"Ottomana"
,"Cuscini"
,"Lavello"
,"Dormeuse"
,"Branda"
,"Toilette"
,"Sgabelli"
,"Scrittoio"
,"Specchio"
]
,"Oggetti3":[
"Pentolame"
,"Posate"
,"Lavandino"
,"Carte"
,"Tavolo da pranzo"
,"Giochi"
,"Bivacco"
,"Whisky"
,"Gabinetto"
,"Spezie"
,"Dispensa"
,"Ganci"
,"Vino"
,"Dadi"
,"Bancone"
,"Birra"
]
,"Oggetti4":[
"Piedistallo"
,"Libro"
,"Candele"
,"Spartiti"
,"Voliera"
,"Poltrona"
,"Dipinti"
,"Tappeto"
,"Vasi"
,"Caminetto"
,"Strumenti"
,"Tende"
,"Statua"
,"Campana"
,"Penna"
]
,"Oggetti5":[
"Armi"
,"Stracci"
,"Bruciatore"
,"Strumenti"
,"Munizioni"
,"Banco da Lavoro"
,"Fiale"
,"Beaker"
,"Strumenti Medici"]
}
,"Luogo":{
    "Luogo":[
    "Draga di Dunslough"
    ,"Ferriera (case popolari) di Coalridge"
    ,"Ponte Bowmore a Brightstone"
    ,"Stazione ferroviaria di Gaddok"
    ,"Sede della guardia cittadina di Brightstone"
    ,"Università di Charterhall"
    ,"Tenute di collina per i supervisori di Barrowcleft"
    ,"Via della cancelleria (strutture governative) Charterhall"
    ,"Archivi degli Echi a Charterhall"
    ,"Ponte Barrow (Barrowcleft)"
    ,"Mercato di Barrowcleft"
    ,"Brkstone (+redisdenziale di Duskwall) a Coalridgeà"
    ,"Gli scampoli (stoffe lavandaie) a Charhollow"
    ,"Vecchio porto 'Nord'"
    ,"Ghetto di Dunslough"
    ,"Da Kellen (pub) Charhollow"
    ,"Groviglia (nave affondata, quartiere galleggiante) a Crow's Foot"
    ,"Fabbrica di binari a Coalridge"
    ,"Campo Lavoro di Dunvil a Dunslough"
    ,"Accampamento di barboni a Crow's Foot"
    ,"Opulento teatro/ristorante a Brightstone"
    ,"Il quartiere dei lavoratori di Barrowcleft"
    ,"Villa capitano d'industria a Charterhall"
    ,"Il nido (quartier generale Corvi) a Crow's Foot"
    ,"Mercado di Charhollow"
    ,"Stazione giubbe blu a Crow's Foot"
    ,"Casa Strathmill (orfanotrofio) a Crow's Foot"
    ,"Accademia della Fusciacca Rossa a Crow's Foot"
    ,"Villa Nobiliare di Wott a Brightstone"
    ,"Le miniere di Barrowcleft"
    ,"Casa Strangford Charhollow"
    ,"Allevamenti di anguille di Dunslough"
    ,"Fabbrica di carrozze a Coalridge"
    ,"Mercato Argenteo di Brightstone"
    ,"Parco Jayan (studenti) Charterhall"
    ,"Il secchio (locale) a Crow's Foot"
    ,"Case forza lavoro (marinai, nocchieri,anguillari...) Charhollow"
    ,"Magazzini adibiti a rivoluzione Charhollow"
    ,"Vecchie Mura di Charterhall"
    ,"Fattoria Radiante di Barrowcleft"
    ,"Crematori di Bellwather Charterhall"
    ,"La melma (cava di fango) Dunslough"
    ,"Case forza lavoro (servità,portuali,allevatori...) Charhollow"
    ,"Il Sanctorium di Brightstone (Estasi Carne)"
    ,"La Ferrovia spettrale a Coalridge"
    ,"Prigione di Ironhook a Dunslough"
    ,"VillaBaracca di Vandra a Dunslough"
    ,"Miniera di Coalridge"
    ,"Parco dell'Unità di Brightstone"
    ,"Vecchio deposito di Coalridge"
    ,"Villa per festa stravagante"
    ,"Il Velo (club lussuoso, strano) Nightmarket"
    ,"Dundridge & Figli (sartoria) Nightmarket"
    ,"Corse di segugi di Vreen Nightmarket"
    ,"Dente del diavolo (taverna, menà alchemico) Nightmarket"
    ,"Una villetta a schiera a Nightmarket"
    ,"Negozi con insegne al neon a Nightmarket"
    ,"Mercante di saponi di lusso a Nightmarket"
    ,"Compagnia di Punta Nord al Porto"
    ,"Largo Inchiostro (tatuatori) al Porto"
    ,"SaltFord e la sua gang(mortaccisua) al Porto"
    ,"Il Serraglio (zoo?) al Porto"
    ,"Stazione al Porto"
    ,"Nave attraccata al Porto"
    ,"Magazzini al Porto"
    ,"Casa Rowan a 6Torri"
    ,"Parco Mistshore (suicidi/infestato) a 6Torri"
    ,"Maniero Scurlock a 6Torri"
    ,"Braccia signora del pianto (dormitorio) a 6Torri"
    ,"Casa abbandonata a 6Torri"
    ,"La prugna dorata (ristorante) a 6Torri"
    ,"Casa di Flint a 6Torri"
    ,"I terreni della Folgore (circo) a Silkshore"
    ,"La bonaccia (negozi e bordelli) a Silkshore"
    ,"Colle Fogrest (comunità bohàmienne) a Silkshore"
    ,"Parco Ankhayat (zona festival) a Silkshore"
    ,"Casa LevYra (legge la mente/futuro) a Silkshore"
    ,"Cervo Argentato (casinà) a Silkshore"
    ,"La Lanterna Rossa (Bordello) a Silkshore"]
}    
,"Persona":{
    "Retaggio":[
    ,"Iruviano"
    ,"Skovlandese"
    ,"Akorosiano"
    ,"Akorosiano"
    ,"Severosia:[no"
    ,"Akorosiano"
    ,"Tycherosiano"
    ,"Akorosiano"
    ,"Akorosiano"
    ,"Akorosiano"
    ,"Skovlandese"
    ,"Isolano"
    ]
    ,"Nome":[
        "Arquo"
        ,"Grine"
        ,"Skannon,"
        ,"Weaver"
        ,"Orlan,"
        ,"Roethe,"
        ,"Cyrene,"
        ,"Casslyn,"
        ,"Crowl"
        ,"Arlyn,"
        ,"Syra"
        ,"Hix"
        ,"Vestine,"
        ,"Cross"
        ,"Odrienne"
        ,"Una"
        ,"Daphnia"
        ,"Amosen,"
        ,"Timoth,"
        ,"Candra,"
        ,"Brena"
        ,"Arvus"
        ,"Myre"
        ,"Polonia"
        ,"Sesereth"
        ,"Lizete,"
        ,"Vey"
        ,"Ashlyn,"
        ,"Veretta"
        ,"Thena"
        ,"Talitha,"
        ,"Milos"
        ,"Veleris"
        ,"Sethla"
        ,"Lenia"
        ,"Carissa"
        ,"Andrel"
        ,"Morlan,"
        ,"Tocker"
        ,"Naria,"
        ,"Lucella"
        ,"Aldo"
        ,"Edlun,"
        ,"Phin"
        ,"Narcus"
        ,"Lauria"
        ,"Arden"
        ,"Stev"
        ,"Emeline"
        ,"Noggs"
        ,"Remira"
        ,"Holtz"
        ,"Vond,"
        ,"Corille,"
        ,"Kelyr,"
        ,"Lorette"
        ,"Volette"
        ,"Kamelin"
        ,"Clave"
        ,"Vaurin,"
        ,"Laudius,"
        ,"Kobb"
        ,"Tesslyn"
        ,"Wester"
        ,"Helles,"
        ,"Ring"
        ,"Cavelle"
        ,"Stavrul"
        ,"Kristov"
        ,"Carro"
        ,"Adric"
        ,"Quess,"
        ,"Lynthia,"
        ,"Bricks"
        ,"Brance,"
        ,"Brace"
        ,"Drav"
        ,"Mara"
        ,"Branon"
        ,"Zamira."
        ]
        ,"alias":[
        "Tintinnio"
        ,"Uncino"
        ,"Corvo"
        ,"Sperone"
        ,"Martello"
        ,"Mazzetta"
        ,"Dozzina"
        ,"Frusta"
        ,"Campanaccio"
        ,"Puleggia"
        ,"Nebbia"
        ,"Acqua cheta"
        ,"Scheggia"
        ,"Squillo"
        ,"Eco"
        ,"Grillo"
        ,"Pistolero"
        ,"Volpe"
        ,"Gramigna"
        ,"Acciarino"
        ,"Rana"
        ,"Splendido"
        ,"Rubino"
        ,"Cuore Tenero"
        ,"Orco"
        ,"Pallida"
        ,"Stecco"
        ,"Croce"
        ,"Canto"
        ,"Insetto"
        ,"ArtiglioAgo"
        ,"Catorcio"
        ,"Ammaccato"
        ,"Scorticatore"
        ,"BrinaMorsa"
        ,"Spire"
        ]
        ,"Cognome":[
        "Strathmill"
        ,"Haig"
        ,"Bowman"
        ,"Walund"
        ,"Athanoch"
        ,"Boden"
        ,"Vale"
        ,"Dalmore"
        ,"Kardera"
        ,"Basran"
        ,"Lomond"
        ,"Morriston"
        ,"Rowan"
        ,"Brogan"
        ,"Dunvil"
        ,"Penderyn"
        ,"Maroden"
        ,"Arran"
        ,"Templeton"
        ,"Ankhayat"
        ,"Farros"
        ,"Hellyers"
        ,"Danfield"
        ,"Skelkallan"
        ,"Tyrconnell"
        ,"Prichard"
        ,"Booker"
        ,"Grine"
        ,"Michter"
        ,"Clelland"
        ,"Clermont"
        ,"Jayan"
        ,"Helker"
        ,"Slane"
        ,"Keel"
        ,"Coleburn"
        ,"Comber"
        ,"Sevoy"
        ,"Welker"
        ,"Daava"
        ,"Breakiron"
        ,"Jeduin"
        ,"Skora"
        ,"Kinclaith"
        ,"Helles"
        ,"Karstas"
        ,"Kessarin"
        ,"Strangford"
        ]    
    ,"Aspetto":[
    "Uomo"
    ,"Donna"
    ,"Donna"
    ,"Ambiguo"
    ,"Uomo"
    ,"Uomo"
    ,"Celato"
    ,"Donna"
    ]
    ,"Aspetto 2":[
    "Consunto"
    ,"Selvaggio"
    ,"Strano"
    ,"Grosso"
    ,"Pallido"
    ,"Basso"
    ,"Sfigurato, Menomato"
    ,"Ombroso"
    ,"Tozzo"
    ,"Giovane"
    ,"Sexy"
    ,"Delicato"
    ,"Alto"
    ,"Capelli Lunghi, Barba, Parrucca"
    ,"Nerboruto"
    ,"Prostetica, Zoppo"
    ,"Ricurvo"
    ,"Paffuto"
    ,"Rasato, Calvo"
    ,"Smilzo"
    ,"Tatuato"
    ,"Ossuto"
    ,"Atletico"
    ,"Elegante"
    ,"Carino"
    ,"Grezzo"
    ,"Logorato"
    ,"Sfregiato"
    ,"Raffinato"
    ,"Occhiali, Monocolo"
    ,"Cesellato"
    ,"Banale"
    ,"Vecchio"
    ,"Appariscente"
    ,"Affascinante"
    ,"Adorabile"
    ]
    ,"stile":[
    "Anfibi da lavoro"
    ,"Drappeggi"
    ,"Cappotto"
    ,"Cappuccio"
    ,"Mantella"
    ,"Gonna e Camicia"
    ,"Guanti Pesanti"
    ,"Uniforme"
    ,"Sedia a Rotelle"
    ,"Camicia"
    ,"Leggings"
    ,"Maschera"
    ,"Cintura Spessa"
    ,"Stampelle"
    ,"Tunica Grezza"
    ,"Pastrano"
    ,"Bretelle"
    ,"Tricorno"
    ,"Mantello corto"
    ,"Pantaloni Eleganti"
    ,"Sciarpa Lunga"
    ,"Completo"
    ,"Bastone"
    ,"Body di Anguilla"
    ,"Abito Aderente"
    ,"Maschera"
    ,"Stivali Morbidi"
    ,"Cappello di lana"
    ,"Grembiule"
    ,"Pelliccia"
    ,"Stracci"
    ,"Cinturone"
    ,"Impermeabile"
    ,"Mantello Pesante"
    ,"Pelli"
    ,"Giacca aderente"
    ,"Stivali Alti"
    ]
    ,"Obiettivi":[
    "Svolta"
    ,"Conoscenza"
    ,"Rispetto"
    ,"Potere"
    ,"Prestigio, Fama"
    ,"Libertà"
    ,"Caos, Distruzione"
    ,"Vendetta"
    ,"Felicità"
    ,"Giustizia"
    ,"Infamia, Paura"
    ,"Potere"
    ,"Successo"
    ,"Piacere"
    ,"Controllo"
    ,"Cooperazione"
    ,"Benessere"
    ,"Autorità"
    ,"Amore"
    ]
    ,"Metodi preferiti":[
    "Furto"
    ,"Lavoro Duro"
    ,"Arcano"
    ,"Sabotaggio"
    ,"Manipolazione"
    ,"Ricatto"
    ,"Lavoro di Squadra"
    ,"Violenza"
    ,"Strategia"
    ,"Legge, Politica"
    ,"Caos"
    ,"Negoziazione"
    ,"Minacce"
    ,"Alchimia"
    ,"Commercio"
    ,"Studio"
    ,"Spionaggio"
    ,"Sotterfugio"
    ]
    ,"Professioni":[
    "Gondoliere"
    ,"Mercante"
    ,"Birraio"
    ,"Artista"
    ,"Criminale"
    ,"Muratore"
    ,"Muratore"
    ,"Ricamatore"
    ,"Carpentiere Navale"
    ,"Calzolaio"
    ,"Muratore"
    ,"Pellaio"
    ,"Panettiere"
    ,"Barbiere"
    ,"Macellaio"
    ,"Autista"
    ,"Pellaio"
    ,"Carpentiere"
    ,"Carpentiere"
    ,"Venditore"
    ,"Impiegato"
    ,"Servitore"
    ,"Messaggero"
    ,"Barbiere"
    ,"Calzolaio"
    ,"Marinaio"
    ,"Autista"
    ,"Impiegato"
    ,"Carradore"
    ,"Mercante"
    ,"Mercante"
    ,"Tipografo"
    ,"Pastore di Capre"
    ,"Vetraio"
    ,"Messaggero"
    ,"Musicista"
    ,"Fabbro"
    ,"Pellaio"
    ,"Pescatore"
    ,"Fabbro"
    ,"Servitore"
    ,"Coltivatore"
    ,"Falegname"
    ,"Barbiere"
    ,"Calzolaio"
    ,"Tappezziere"
    ,"Secondino"
    ,"Criminale"
    ,"Birraio"
    ,"Tessitore"
    ,"Criminale"
    ,"Tintore"
    ,"Cordaio"
    ,"Ricamatore"
    ,"Fabbro"
    ,"Pellaio"
    ,"Tappezziere"
    ,"Gondoliere"
    ,"Carradore"
    ,"Marinaio"
    ,"Messaggero"
    ,"Tappezziere"
    ,"difensore"
    ,"Mercante"
    ,"Tessitore"
    ,"Pastore di Capre"
    ,"Droghiere"
    ,"Inventore"
    ,"Ripara tetti"
    ,"Impiegato"
    ,"Coltivatore"
    ,"Barbiere"
    ,"Calzolaio"
    ,"Panettiere"
    ,"Barbiere"
    ,"Pescatore"
    ,"Servitore"
    ,"Falegname"
    ,"Pastore di Capre"
    ,"Tessitore"
    ,"Muratore"
    ,"Pellaio"
    ,"Servitore"
    ,"Tappezziere"
    ,"Carradore"
    ,"Sarto"
    ,"Architetto"
    ,"Inventore"
    ,"Tessitore"
    ,"Carradore"
    ,"Servitore"
    ,"Calzolaio"
    ,"Falegname"
    ,"Impiegato"
    ,"Ricamatore"
    ,"Criminale"
    ,"Muratore"
    ,"Venditore"
    ,"Carpentiere Navale"
    ,"Messaggero"
    ,"Esploratore"
    ,"Carpentiere"
    ,"Falegname"
    ,"Gondoliere"
    ,"Mercante"
    ,"Barbiere"
    ,"Cordaio"
    ,"Carpentiere"
    ,"Muratore"
    ,"Bottaio"
    ,"Autista"
    ,"Carradore"
    ,"Carpentiere"
    ,"Banchiere"
    ,"Panettiere"
    ,"Messaggero"
    ,"Carpentiere"
    ,"Tessitore"
    ,"Tesoriere"
    ,"Carpentiere Navale"
    ,"Venditore"
    ,"Fabbro"
    ,"Tappezziere"
    ,"Inventore"
    ,"Inventore"
    ,"Carradore"
    ,"Bottaio"
    ,"Impiegato"
    ,"Ripara tetti"
    ,"Carradore"
    ,"Droghiere"
    ,"Guardia"
    ,"Pellaio"
    ,"Guardia"
    ,"Guardia"
    ,"Tintore"
    ,"Macellaio"
    ,"Panettiere"
    ,"Carpentiere"
    ,"Panettiere"
    ,"Scrivano"
    ,"Pescatore"
    ,"Sarto"
    ,"Cerusico"
    ,"Marinaio"
    ,"Panettiere"
    ,"Autista"
    ,"Droghiere"
    ,"Pellicciaio"
    ,"Criminale"
    ,"Criminale"
    ,"Mercante"
    ,"Gondoliere"
    ,"Guardia"
    ,"Tessitore"
    ,"Cortigiano"
    ,"Cordaio"
    ,"Esattore"
    ,"Bottaio"
    ,"Pescatore"
    ,"Pastore di Capre"
    ,"Cordaio"
    ,"Calzolaio"
    ,"Gondoliere"
    ,"Carradore"
    ,"Coltivatore"
    ,"Calzolaio"
    ,"Muratore"
    ,"Mastro di Chiavi"
    ,"Guardia"
    ,"Avvocato"
    ,"Idraulico"
    ,"Cordaio"
    ,"Tappezziere"
    ,"Bottaio"
    ,"Birraio"
    ,"Fabbro"
    ,"Sanguisuga"
    ,"Pescatore"
    ,"Inventore"
    ,"Coltivatore"
    ,"Guardia"
    ,"Servitore"
    ,"Cordaio"
    ,"Conciatore"
    ,"Autista"
    ,"Messaggero"
    ,"Mercante"
    ,"Sarto"
    ,"Criminale"
    ,"Tintore"
    ,"Birraio"
    ,"Ricamatore"
    ,"Birraio"
    ,"Impiegato"
    ,"Apicoltore"
    ,"Tintore"
    ,"Venditore"
    ,"Marinaio"
    ,"Gondoliere"
    ,"Cordaio"
    ,"Carpentiere Navale"
    ,"Macellaio"
    ,"Carpentiere Navale"
    ,"Messaggero"
    ,"Barbiere"
    ,"Venditore"
    ,"Conciatore"
    ,"Tessitore"
    ,"Tintore"
    ,"Compositore"
    ,"Panettiere"
    ,"Falegname"
    ,"Mercante"
    ,"Gondoliere"
    ,"Carpentiere"
    ,"Macellaio"
    ,"Guardia"
    ,"Droghiere"
    ,"Gondoliere"
    ,"Barbiere"
    ,"Sarto"
    ,"Ricamatore"
    ,"Diplomatico"
    ,"Sarto"
    ,"Pastore di Capre"
    ,"Bottaio"
    ,"Tintore"
    ,"Calzolaio"
    ,"Servitore"
    ,"Accademico"
    ,"Messaggero"
    ,"Folgoratore"
    ,"Conciatore"
    ,"Muratore"
    ,"Pescatore"
    ,"Conciatore"
    ,"Carpentiere Navale"
    ,"Ricamatore"
    ,"Carpentiere Navale"
    ,"Bottaio"
    ,"Macellaio"
    ,"Guardia"
    ,"Pastore di Capre"
    ,"Fabbro"
    ,"Bottaio"
    ,"Tintore"
    ,"Sceriffo"
    ,"Coltivatore"
    ,"Macellaio"
    ,"Macellaio"
    ,"Cordaio"
    ,"Venditore"
    ,"Fabbro"
    ,"Coltivatore"
    ,"Coltivatore"
    ,"Cordaio"
    ,"Impiegato"
    ,"Tintore"
    ,"Carpentiere Navale"
    ,"Pescatore"
    ,"Cacciatore di taglie"
    ,"Macellaio"
    ,"Criminale"
    ,"Conciatore"
    ,"Carradore"
    ,"Calzolaio"
    ,"Carpentiere"
    ,"Conciatore"
    ,"Carpentiere"
    ,"Tintore"
    ,"Carradore"
    ,"Impiegato"
    ,"Pastore di Capre"
    ,"Pastore di Capre"
    ,"Messaggero"
    ,"Droghiere"
    ,"Ripara tetti"
    ,"Ripara tetti"
    ,"Tessitore"
    ,"Macellaio"
    ,"Tintore"
    ,"Coltivatore"
    ,"Birraio"
    ,"Conciatore"
    ,"Falegname"
    ,"Sarto"
    ,"Marinaio"
    ,"Orologiaio"
    ,"Ripara tetti"
    ,"Coltivatore"
    ,"Panettiere"
    ,"Sarto"
    ,"Impiegato"
    ,"Guardia"
    ,"Falegname"
    ,"Bottaio"
    ,"Inventore"
    ,"Pellaio"
    ,"Autista"
    ,"Tappezziere"
    ,"Autore"
    ,"Magistrato"
    ,"Muratore"
    ,"Funzionario"
    ,"Tappezziere"
    ,"Fabbro"
    ,"Conciatore"
    ,"Droghiere"
    ,"Venditore"
    ,"Servitore"
    ,"Carpentiere Navale"
    ,"Ripara tetti"
    ,"Ripara tetti"
    ,"Autista"
    ,"Capitano"
    ,"Panettiere"
    ,"Birraio"
    ,"Marinaio"
    ,"Tessitore"
    ,"Pellaio"
    ,"Sarto"
    ,"Sarto"
    ,"Ripara tetti"
    ,"Gondoliere"
    ,"Mercante"
    ,"Marinaio"
    ,"Birraio"
    ,"Inventore"
    ,"Gioielliere"
    ,"Droghiere"
    ,"Marinaio"
    ,"Cordaio"
    ,"Falegname"
    ,"Ricamatore"
    ,"Guardiano di Spiriti"
    ,"Messaggero"
    ,"Servitore"
    ,"Birraio"
    ,"Panettiere"
    ,"Calzolaio"
    ,"Venditore"
    ,"Venditore"
    ,"Fabbro"
    ,"Criminale"
    ,"Ricamatore"
    ,"Pastore di Capre"
    ,"Venditore"
    ,"Barbiere"
    ,"Falegname"
    ,"Criminale"
    ,"Soldato"
    ,"Fabbro"
    ,"Marinaio"
    ,"Pescatore"
    ,"Conciatore"
    ,"Ripara tetti"
    ,"Ricamatore"
    ,"Muratore"
    ,"Pellaio"
    ,"Ricamatore"
    ,"Pellaio"
    ,"Inventore"
    ,"Tessitore"
    ,"Gondoliere"
    ,"Falegname"
    ,"Ripara tetti"
    ,"Inventore"
    ,"Guardarotaie"
    ,"Macellaio"
    ,"Droghiere"
    ,"Servitore"
    ,"Mercante"
    ,"Droghiere"
    ,"Barbiere"
    ,"Autista"
    ,"Birraio"
    ,"Tappezziere"
    ,"Impiegato"
    ,"Inventore"
    ,"Droghiere"
    ,"Coltivatore"
    ,"Pescatore"
    ,"Autista"
    ,"Bottaio"
    ,"Pescatore"
    ,"Guardia"
    ,"Carpentiere Navale"
    ,"Pastore di Capre"
    ,"Sarto"
    ,"Tappezziere"
    ,"Autista"
    ,"Giornalista"
    ,"Conciatore"
    ,"Marinaio"
    ,"Bottaio"
    ,"Sussurro"
    ]
    ,"TRATTI":[
    "Ossessivo"
    ,"Sospettoso"
    ,"Calcolatore"
    ,"Crudele"
    ,"Incantevole"
    ,"Lunatico"
    ,"Candido"
    ,"Paranoico"
    ,"Enigmatico"
    ,"Accorto"
    ,"Sofisticato"
    ,"Sprezzante"
    ,"Cooperativo"
    ,"Malinconico"
    ,"Spavaldo"
    ,"Disonesto"
    ,"Reticente"
    ,"Elitario"
    ,"Agguerrito"
    ,"Vanitoso"
    ,"Audace"
    ,"Subdolo"
    ,"Sicuro di sé"
    ,"Cortese"
    ,"Paziente"
    ,"Arrogante"
    ,"Volatile"
    ,"Freddo"
    ,"Crudele"
    ,"Entusiasta"
    ,"Perspicace"
    ,"Cavaliere"
    ,"Tranquillo"
    ,"Noncurante"
    ,"Avventato"
    ,"Calmo"
    ]
    ,"INTERESSI":[
    "Buon whisky, vino, birra"
    ,"La Signora del Pianto, beneficienza"
    ,"Filosofia naturale"
    ,"Combattimenti, duelli"
    ,"Esplorazioni, avventure"
    ,"Alchimia, medicina"
    ,"Amanti, romanticismo, tresche"
    ,"Storie sui demoni, leggende"
    ,"Bei vestiti, gioielli, pellicce"
    ,"Leggende pre-cataclisma"
    ,"Cucinare, giardinaggio"
    ,"Feste, eventi sociali"
    ,"Sentiero degli Echi"
    ,"Poesia, novelle, scrittura"
    ,"Droghe, essenze, tabacco"
    ,"Cavalli, cavalcare"
    ,"Antichità, artefatti, curiosità"
    ,"Gadgets, nuove tecnologie"
    ,"Storia, leggende"
    ,"Belle arti, opera, teatro"
    ,"Architettura, arredamenti"
    ,"Libri Arcani, rituali"
    ,"Navi, nautica"
    ,"Collezionista di armi"
    ,"Artigianato (pellame, ecc.)"
    ,"Dei Dimenticati"
    ,"Musica, strumenti, danza"
    ,"Animali (uccelli,cani, gatti)"
    ,"Caccia, tiro a segno"
    ,"Essenze, alchimia"
    ,"Quadri, dipinti, sculture"
    ,"Chiesa dell?Estasi"
    ,"Spettrologia, elettroplasma"
    ,"Buon cibo, ristoranti"
    ,"Gioco d?azzardo, carte, dadi"
    ,"Politica, giornalismo"
    ]
    ,"PARTICOLARI":[
    "Rivoluzionario. Complotta contro l?Imperium."
    ,"Ciecamente fedele a un ideale, gruppo, o tradizione."
    ,"Recluso. Preferisce interagire tramite messaggeri."
    ,"In prigione o sotto l?arresto di una nobile casata."
    ,"Reputazione scandalosa (meritata o meno)."
    ,"Si preoccupa del suo aspetto, pettegolezzi, i suoi pari."
    ,"Orgoglioso del retaggio, tradizioni, lingua nativa."
    ,"Fanno affidamento al Consiglio per prendere decisioni."
    ,"Superstizioso. Crede nei segni, numeri magici."
    ,"Ricoprono il loro ruolo grazie al ricatto."
    ,"Carica ereditaria. Forse non la meritano/desiderano."
    ,"Un simulacro riformato. Immune agli spiriti"
    ,"Celebrità. Reso popolare dalla stampa /musica / teatro."
    ,"Ha un diario dettagliato, appunti, archivi, registri."
    ,"Devoto alla famiglia."
    ,"Abusa di droghe/alchol. Spesso debilitato dai vizi."
    ,"Navigato. Conoscenze fuori da Doskvol."
    ,"Coinvolto in crimini di guerra dalla Guerra dell?Unità."
    ,"Usa la sua carica per spiare per un?altra fazione."
    ,"Debiti enormi (alle banche / criminali / famiglia)"
    ,"Ha una malattia cronica e richiede cure continue."
    ,"Controllato in segreto (o no?) da uno spirito possessore."
    ,"Circondato da adulatori, supplicanti, tirapiedi."
    ,"Pecora nera/reietto da una famiglia o organizzazione."
    ,"Non vede i difetti negli amici, alleati, famigliari, ecc."
    ,"Visionario. Ha idee radicali per il futuro."
    ,"Maledetto, tormentato, vessato da spiriti o demone."
    ,"Pregiudizi contro culture / convinzione / classe sociale."
    ,"Sposato in una famiglia importante/potente."
    ,"Impostore. Un aspetto importante è inventato."
    ,"Fermo tradizionalista. Si oppone a nuove idee."
    ,"Reputazione impeccabile. Altamente considerato."
    ,"Ampia educazione su ogni argomento accademico."
    ,"Ha una doppia vita grazie a un?identità segreta."
    ,"Intenso, fobia o odio irrazionale."
    ,"Aiuta i progetti di un demone (coscientemente o no)"
    ]
    ,"Tycheros traits":[
    "coda da demone"
    ,"ombra in ritardo di mezzo secondo"
    ,"ali da demone"
    ,"pupille a taglio"
    ,"3 file di denti"
    ,"escrescenze ossee"
    ,"corna di pietra"
    ,"fumo dagli occhi"
    ,"occhi neri"
    ,"4 occhi"
    ,"pelle di colore strano"
    ,"articolazioni delle gambe invertite"
    ,"tatuaggi blu cangianti"
    ]
    }    
}

const rawDataHit = {
    "Bande":
    {
        "assassini":[]
    }
    ,"Il Colpo": {
        "riassunto":
            [`Un bersaglio. Ministero della Conservazione.\n
            Un luogo. Uno dei magazzini per lo stoccaggio del contrabbando vicino alla Stazione Gaddoc.\n
            Una situazione. Una rete di contrabbando di essenza di spirito, proprio ieri, è stata beccata dai Guardiani presso la Stazione di Gaddoc.\n
            Un vettore ovvio per il piano. Laroze può farsi assumere in nero come guardia privata. Vi farà entrare dal retro, per una fetta dei guadagni.\n
            \n
            Informazioni più precise:\n
            Fazioni collegate e cosa vogliono o necessitano. Quell’essenza era stata pagata dall’Alveare. Vogliono ciò che è loro.\n
            Un vettore non così scontato per il piano. Le essenze di spirito possono essere richiamate attraverso il campo spettrale... in teoria.\n
            Segreti interessanti, un collegamento a un’opportunità alternativa. È molto probabile che i Guardiani mettano in sicurezza l’essenza catturata con protezioni arcane. I Riconciliati aborrono lo scambio di essenza e potrebbero essere un potenziale alleato o nemico, a seconda di quello farete.\n`],
        "Opportunità":[
            "I vostri clienti più prestigiosi sono stanchi di venire nel vostro territorio per una dose. Create una vetrina in una parte più onesta della città (o al contrario per i clienti di classe sociale inferiore)."
            ,"Il culto di un dio dimenticato vi fa un'offerta per una collaborazione: possono rendere il vostro prodotto più appetibile in cambio di... un trattamento speciale."
            ,"Una nobile dilettante sempre sulla cresta dell'onda sta bazzicando nella vostra area con il suo entourage di leccapiedi, in cerca della 'prossima hit' da provare."
            ,"Un ardente predicatore fa proclami contro il vostro prodotto per le strade, abbassando la richiesta. Ma vi sembra di riconoscerlo come un vostro cliente..."
            ,"La gang che operava sul vostro territorio anni fa è tornata dalle Isole del Pugnale e si aspetta di tornare ai suoi affari come se nulla fosse."
            ,"Inizia ad apparire nelle strade un'imitazione del vostro prodotto, a un prezzo ribassato. Il vostro fornitore vi sta tagliando fuori'"
            ,"I trafficanti vogliono eliminare tutti gli intermediari nella filiera e gestire le cose direttamente con voi."
            ,"I fantasmi dei vostri 'ex' clienti sono improvvisamente richiamati a voi, smaniosi per la loro dose."
            ,"Una famigerata cacciatrice di leviatani ha gusti che... solitamente non soddisfate, ma è disposta a pagare davvero molto bene."
            ,"Una Giubba Blu ha ucciso il suo ultimo spacciatore per aver 'spinto troppo in là il loro rapporto', e si rivolge alla banda come fonte alternativa."
            ,"Una brutale gang di feroci assassini ha 'ripulito' il covo del vizio di un rivale. Ora vogliono che siate voi a occuparvi della gestione."
            ,"Una figura mascherata vi paga profumatamente per l'opportunità di uccidere uno dei vostri clienti abituali mentre è... distratto."
            ,"Un assassino arcano sta bersagliando fruitori e spacciatori, lasciando Simulacri a vagare per la città."
            ,"Un operatore solitario sta distribuendo una versione molto più popolare del vostro prodotto."
            ,"Un membro del Consiglio Cittadino sta mettendo al vaglio un divieto assoluto per un prodotto illecito; potrebbero farsi convincere a fare in modo che sia il vostro, mandando la domanda alle stelle."
            ,"Una nuova gang del vizio sta facendo delle mosse molto scaltre e intelligenti. Le voci dicono che siano guidati dal fantasma di un criminale leggendario."
            ,"Gli studenti dell'Accademia di Doskvol hanno dimostrato interesse per la vostra merce, ma dovete consegnarla direttamente, superando la sicurezza gestita dalle Giubbe Blu."
            ,"Un leggendario truffatore e la sua banda stanno colpendo diversi magazzini. È stata messa una taglia sulle loro teste: riuscirete a rivendicarla'"
        ],
        "Cliente/Bersaglio":[
            "Nobile"
            ,"Ufficiale"
            ,"Banchiere"
            ,"Capitano"
            ,"Posseduto"
            ,"Simulacro"
            ,"Accademico"
            ,"Studioso"
            ,"Vampiro"
            ,"altro Non Morto"
            ,"Sacerdote"
            ,"Cultista"
            ,"Dottore"
            ,"Alchimista"
            ,"Mercenario"
            ,"Teppista"
            ,"Rivoluzionario"
            ,"Rifugiato"
            ,"Spacciatore"
            ,"Fornitore"
            ,"Corriere"
            ,"Marinaio"
            ,"Spia"
            ,"Informatore"
            ,"Ricettatore"
            ,"Scommetitore"
            ,"Boss Criminale"
            ,"Mercante"
            ,"Negoziante"
            ,"Fantasma di (tira ancora)"
            ,"Sussurro"
            ,"Cultista"
            ,"Trafficante"
            ,"Ladro"
            ,"Manovale"
            ,"Commerciante"
            ,"Artista"
            ,"Scrittore"
            ,"Magistrato"
            ,"Capo Distretto"
            ,"Demone (mascherato)"
            ,"Collezionista Occulto"
            ,"Conestabile"
            ,"Ispettore"            
        ],
        "lavoro":[
            "Raccolta"
,"Piazzamento"
,"Impersona"
,"Depista"
,"Distruggi"
,"Deturpa"
,"Crea"
,"Rianima un Simulacro"
,"Rapina"
,"Furto"
,"Rapina"
,"Rapina a mano armata"
,"Terrorizza"
,"Estorici"
,"Incursione"
,"Difesa"
,"Estrai Essenza"
,"Trova"
,"Nascondi"
,"Piazza"
,"Rimuovi Rune"
,"Avvelena"
,"Simula Incidente"
,"Scorta"
,"Sicurezza"
,"Cerimonia / Ferma un Rituale"
,"Bandisci"
,"Evoca"
,"Pedinamento"
,"Sorveglianza"
,"Sabotaggio"
,"Dolo"
,"Sparizione"
,"Riscatto"
,"Ricatta"
,"Discredita"
,"Maledici"
,"Santifica"
,"Assasinio"
,"Contrabbando"
,"Corriere"
,"Truffa"
,"Spionaggio"
,"Negozia"
,"Minaccia"
        ],
        "modifica o complicazione":[
            "Un elemento e' una copertura perpratiche eretiche di un culto"
,"Il lavoro e' un test per un lavoro successivo"
,"Il luogo si muove (il sito cambia, e' suun veicolo, ecc.)"
,"Il lavoro richiede un viaggio in mare"
,"Il lavoro porta avanti gli interessi segruenti di un prestigioso mercante"
,"Il lavoro richiede di viaggiare in elettrotreno"
,"Il lavoro porta avanti gli interessi segreti di un vampiro"
,"Il luogo e' usato da una gang pericolosa"
,"Il lavoro porta avanti gli interessi segreti di un boss criminale"
,"Un elemento e' un facciata per un'impresa criminale"
,"Il lavoro porta avanti gli interessi segreti di un ufficiale cittadino"
,"Il lavoro porta avanti gli interessi segreti di un demone"
,"Bisogna visitare le Terre Morte"
,"Il lavoro porta avanti gli interessi segreti di un rivoluzionario"
,"Spiriti impazziti posseggono alcuni/molti/tutti o coinvolti"
,"Un occultista ha previsto il colpo e ha avvertito le parti interessate"
,"Spiriti impazziti infestano il luogo"
,"Il lavoro e' una trappola impostata dai vostri nemici"

        ],
        "LEGATO A UNA PERSONA":[
            ,"Strano Fantasma, Demone, Dio"
,"PG Amico"
,"PG Rivale"
,"PG Fornitore del Vizio"
,"Città Volto noto di Doskvol"
,"Banda Contatto"
        ],
        "E FAZIONI":[
            "Ulf Ironborn"
        ,"Marinai o Portuali"
        ,"Cacciatori di Leviatani"
        ,"Lord Scurlock"
        ,"Ministero della Conservazione"
        ,"Il Consiglio o LaFondazione"
        ,"Rifugiati Skovlanesi"
        ,"Gli Dei Dimenticati"
        ,"Folgoratori"
        ,"Esercito Imperiale"
        ,"Guardarotaie o La Brigata"
        ,"Un Consolato"
        ,"Le Giubbe Grigie"
        ,"Gli Spettri"
        ,"Le Fioche Sorelle"
        ,"Sentiero o Riconciliati"
        ,"Messi o Gazzettini"
        ,"La Chiesa dell'Estasi"
        ,"Predoni delle Terre Morte"
        ,"Giubbe Blu o Ispettori"
        ,"Guardiani diSpiriti"
        ,"Le Fusciacche Rosse"
        ,"Il Circolo della Fiamma"
        ,"Le Roncole"
        ,"La Signoradel Pianto"
        ,"I Corvi"
        ,"I Perduti"
        ,"I Lampionari"
        ,"I Segugi della Nebbia"
        ,"Prigione di Ironhook"
        ,"Tritasangue"
        ,"Operai o Servitori"
        ,"L'Alveare"
        ,"Gondolieri o Nocchieri"
        
        ]
    }
}